#pragma once


//{{Redefine Class Section
#define Ac3dDwfNavTreeNode Gc3dDwfNavTreeNode
#define	AcApDataManager 	GcApDataManager
#define	AcApDocManager 	GcApDocManager
#define	AcApDocManagerReactor 	GcApDocManagerReactor
#define	AcApDocument 	GcApDocument
#define	AcApDocumentIterator 	GcApDocumentIterator
#define	AcApLayoutManager 	GcApLayoutManager
#define	AcApLongTransactionManager 	GcApLongTransactionManager
#define	AcApLongTransactionReactor 	GcApLongTransactionReactor
#define	AcApProfileManagerReactor GcApProfileManagerReactor
#define	AcApProfileNameArray GcApProfileNameArray
#define	AcArray 	GcArray
#define	AcArrayMemCopyReallocator 	GcArrayMemCopyReallocator
#define	AcArrayObjectCopyReallocator 	GcArrayObjectCopyReallocator

// FOR VBA
#define AcRxDynPropManager  GcRxDynPropManager
#define AcAxGetOleLinkManager   GcAxGetOleLinkManager
#define	AcAxDocLock 	GcAxDocLock
#define	AcAxMatrix3d 	GcAxMatrix3d
#define	AcAxPoint2d 	GcAxPoint2d
#define	AcAxPoint2dArray 	GcAxPoint2dArray
#define	AcAxPoint3d 	GcAxPoint3d
#define	AcAxPoint3dArray 	GcAxPoint3dArray
#define AcAxErase GcAxErase
#define AcAxSetXData GcAxSetXData
#define AcAxGetXData GcAxGetXData
#define AcAxGetObjectName GcAxGetObjectName
#define AcAxGetHandle GcAxGetHandle
#define AcAxGetColor GcAxGetColor
#define AcAxPutColor GcAxPutColor
#define AcAxGetTrueColor GcAxGetTrueColor
#define AcAxPutTrueColor GcAxPutTrueColor
#define AcAxGetLayer GcAxGetLayer
#define AcAxPutLayer GcAxPutLayer
#define AcAxGetLinetype GcAxGetLinetype
#define AcAxPutLinetype GcAxPutLinetype
#define AcAxGetShadowDisplay GcAxGetShadowDisplay
#define AcAxPutShadowDisplay GcAxPutShadowDisplay
#define AcAxGetMaterial GcAxGetMaterial
#define AcAxPutMaterial GcAxPutMaterial
#define AcAxGetLinetypeScale GcAxGetLinetypeScale
#define AcAxPutLinetypeScale GcAxPutLinetypeScale
#define AcAxGetVisible GcAxGetVisible
#define AcAxPutVisible GcAxPutVisible
#define AcAxArrayPolar GcAxArrayPolar
#define AcAxArrayRectangular GcAxArrayRectangular
#define AcAxHighlight GcAxHighlight
#define AcAxCopy GcAxCopy
#define AcAxMove GcAxMove
#define AcAxRotate GcAxRotate
#define AcAxRotate3D GcAxRotate3D
#define AcAxMirror GcAxMirror
#define AcAxMirror3D GcAxMirror3D
#define AcAxScaleEntity GcAxScaleEntity
#define AcAxTransformBy GcAxTransformBy
#define AcAxUpdate GcAxUpdate
#define AcAxGetBoundingBox GcAxGetBoundingBox
#define AcAxIntersectWith GcAxIntersectWith
#define AcAxGetPlotStyleName GcAxGetPlotStyleName
#define AcAxPutPlotStyleName GcAxPutPlotStyleName
#define AcAxGetLineWeight GcAxGetLineWeight
#define AcAxPutLineWeight GcAxPutLineWeight
#define AcAxHasExtensionDictionary GcAxHasExtensionDictionary
#define AcAxGetExtensionDictionary GcAxGetExtensionDictionary
#define AcAxGetDatabase GcAxGetDatabase
#define AcAxGetOwnerId GcAxGetOwnerId
#define AcAxGetIUnknownOfObject GcAxGetIUnknownOfObject
#define AcAxEnableShadowDisplay GcAxEnableShadowDisplay
#define IAcPiCategorizePropertiesImpl	IGcPiCategorizePropertiesImpl
#define	ACAD_OPMPROPMAP_ENTRY	GCAD_OPMPROPMAP_ENTRY
#define AcShadowDisplayType	GcShadowDisplayType
#define ACAD_LWEIGHT		GCAD_LWEIGHT
#define IAcadShadowDisplay 	IGcadShadowDisplay
#define AcColorMethod		GcColorMethod
#define AcColor			GcColor
#define ACAD_COLOR		GCAD_COLOR
// END VBA

#define	AcCm 	GcCm
#define	AcCmColor 	GcCmColor
#define	AcCmEntityColor 	GcCmEntityColor
#define	AcCmTransparency 	GcCmTransparency
#define	AcDb2LineAngularDimension 	GcDb2LineAngularDimension
#define	AcDb2dPolyline 	GcDb2dPolyline
#define	AcDb2dVertex 	GcDb2dVertex
#define	AcDb3PointAngularDimension 	GcDb3PointAngularDimension
#define	AcDb3dPolyline 	GcDb3dPolyline
#define	AcDb3dPolylineVertex 	GcDb3dPolylineVertex
#define	AcDb3dSolid 	GcDb3dSolid
#define	AcDbAbstractViewTable 	GcDbAbstractViewTable
#define	AcDbAbstractViewTableIterator 	GcDbAbstractViewTableIterator
#define	AcDbAbstractViewTableRecord 	GcDbAbstractViewTableRecord
#define	AcDbAlignedDimension 	GcDbAlignedDimension
#define	AcDbAppEntityGrips GcDbAppEntityGrips
#define	AcDbAppSystemVariables 	GcDbAppSystemVariables
#define	AcDbArc 	GcDbArc
#define	AcDbArcAlignedText 	GcDbArcAlignedText
#define	AcDbAttribute 	GcDbAttribute
#define	AcDbAttributeDefinition 	GcDbAttributeDefinition
#define	AcDbAuditInfo 	GcDbAuditInfo
#define	AcDbBlockBegin 	GcDbBlockBegin
#define	AcDbBlockChangeIterator 	GcDbBlockChangeIterator
#define	AcDbBlockEnd 	GcDbBlockEnd
#define	AcDbBlockInsertionPoints GcDbBlockInsertionPoints
#define	AcDbBlockReference 	GcDbBlockReference
#define	AcDbBlockReferenceIdIterator 	GcDbBlockReferenceIdIterator
#define	AcDbBlockTable 	GcDbBlockTable
#define	AcDbBlockTableIterator 	GcDbBlockTableIterator
#define	AcDbBlockTablePointer 	GcDbBlockTablePointer
#define	AcDbBlockTableRecord 	GcDbBlockTableRecord
#define	AcDbBlockTableRecordIterator 	GcDbBlockTableRecordIterator
#define	AcDbBlockTableRecordPointer 	GcDbBlockTableRecordPointer
#define	AcDbBody 	GcDbBody
#define	AcDbCircle 	GcDbCircle
#define	AcDbCompositeFilteredBlockIterator 	GcDbCompositeFilteredBlockIterator
#define	AcDbCurve 	GcDbCurve
#define	getAcGeCurve 	getOdGeCurve
#define	createFromAcGeCurve 	createFromOdGeCurve
#define	AcDbCustomOsnapInfo 	GcDbCustomOsnapInfo
#define	AcDbCustomOsnapManager 	GcDbCustomOsnapManager
#define	AcDbCustomOsnapMode 	GcDbCustomOsnapMode
#define	AcDbDatabase 	GcDbDatabase
#define	AcDbDatabaseIterator 	GcDbDatabaseIterator
#define	AcDbDatabaseReactor 	GcDbDatabaseReactor
#define	AcDbDatabaseSummaryInfo 	GcDbDatabaseSummaryInfo
#define	AcDbDate 	GcDbDate
#define	AcDbDeepCloneFiler 	GcDbDeepCloneFiler
#define	AcDbDiametricDimension 	GcDbDiametricDimension
#define	AcDbDictUtil 	GcDbDictUtil
#define	AcDbDictionary 	GcDbDictionary
#define	AcDbDictionaryIterator 	GcDbDictionaryIterator
#define	AcDbDictionaryPointer 	GcDbDictionaryPointer
#define	AcDbDictionaryWithDefault 	GcDbDictionaryWithDefault
#define	AcDbDimData 	GcDbDimData
#define	AcDbDimDataArray 	GcDbDimDataArray
#define	AcDbDimDataPtrArray 	GcDbDimDataPtrArray
#define	AcDbDimStyleTable 	GcDbDimStyleTable
#define	AcDbDimStyleTableIterator 	GcDbDimStyleTableIterator
#define	AcDbDimStyleTablePointer 	GcDbDimStyleTablePointer
#define	AcDbDimStyleTableRecord 	GcDbDimStyleTableRecord
#define	AcDbDimStyleTableRecordPointer 	GcDbDimStyleTableRecordPointer
#define	AcDbDimension 	GcDbDimension
#define	AcDbDoubleClickEdit 	GcDbDoubleClickEdit
#define	AcDbDwgFiler 	GcDbDwgFiler
#define	AcDbDxfFiler 	GcDbDxfFiler
#define	AcDbDynBlockReference 	GcDbDynBlockReference
#define AcDbDynBlockTableRecord GcDbDynBlockTableRecord
#define	AcDbEllipse 	GcDbEllipse
#define	AcDbEntity 	GcDbEntity
#define	AcDbEntityHyperlinkPE 	GcDbEntityHyperlinkPE
#define	AcDbEntityPointer 	GcDbEntityPointer
#define	AcDbEntityReactor 	GcDbEntityReactor
#define	AcDbExtents 	GcDbExtents
#define	AcDbFace 	GcDbFace
#define	AcDbFaceRecord 	GcDbFaceRecord
#define	AcDbFcf 	GcDbFcf
#define	AcDbField 	GcDbField
#define AcDbFieldArray GcDbFieldArray
#define	AcDbFilter 	GcDbFilter
#define	AcDbFilteredBlockIterator 	GcDbFilteredBlockIterator
#define	AcDbFrame 	GcDbFrame
#define	AcDbFullSubentPath 	GcDbFullSubentPath
#define	AcDbFullSubentPathArray 	GcDbFullSubentPathArray
#define	AcDbGraph 	GcDbGraph
#define	AcDbGraphNode 	GcDbGraphNode
#define	AcDbGraphStack 	GcDbGraphStack
#define	AcDbGripData 	GcDbGripData
#define	AcDbGripDataArray 	GcDbGripDataArray
#define	AcDbGripDataPtrArray 	GcDbGripDataPtrArray
#define AcDbMultiModesGripPE GcDbMultiModesGripPE
#define	AcDbGroup 	GcDbGroup
#define	AcDbGroupIterator 	GcDbGroupIterator
#define	AcDbHandle 	GcDbHandle
#define	AcDbHardOwnershipId 	GcDbHardOwnershipId
#define	AcDbHardPointerId 	GcDbHardPointerId
#define	AcDbHatch 	GcDbHatch
#define	AcDbHostApplicationProgressMeter 	GcDbHostApplicationProgressMeter
#define	AcDbHostApplicationServiceRestrictions 	GcDbHostApplicationServiceRestrictions
#define	AcDbHostApplicationServices 	GcDbHostApplicationServices
#define	AcDbHyperlink 	GcDbHyperlink
#define	AcDbHyperlinkCollection 	GcDbHyperlinkCollection
#define	AcDbIdMapping 	GcDbIdMapping
#define	AcDbIdMappingIter 	GcDbIdMappingIter
#define	AcDbIdPair 	GcDbIdPair
#define	AcDbImage 	GcDbImage
#define	AcDbIndex 	GcDbIndex
#define	AcDbIndexUpdateData 	GcDbIndexUpdateData
#define	AcDbIndexUpdateDataIterator 	GcDbIndexUpdateDataIterator
#define	AcDbIntArray 	GcDbIntArray
#define AcDbArrayIntArray GcDbArrayIntArray
#define	AcDbLayerFilter 	GcDbLayerFilter
#define	AcDbLayerIndex 	GcDbLayerIndex
#define	AcDbLayerIndexIterator 	GcDbLayerIndexIterator
#define	AcDbLayerTable 	GcDbLayerTable
#define	AcDbLayerTableIterator 	GcDbLayerTableIterator
#define	AcDbLayerTablePointer 	GcDbLayerTablePointer
#define	AcDbLayerTableRecord 	GcDbLayerTableRecord
#define	AcDbLayerTableRecordPointer 	GcDbLayerTableRecordPointer
#define	AcDbLayout 	GcDbLayout
#define	AcDbLayoutManager 	GcDbLayoutManager
#define	AcDbLayoutManagerReactor 	GcDbLayoutManagerReactor
#define	AcDbLeader 	GcDbLeader
#define	AcDbLight 	GcDbLight
#define	AcDbLine 	GcDbLine
#define	AcDbLinetypeTable 	GcDbLinetypeTable
#define	AcDbLinetypeTableIterator 	GcDbLinetypeTableIterator
#define	AcDbLinetypeTablePointer 	GcDbLinetypeTablePointer
#define	AcDbLinetypeTableRecord 	GcDbLinetypeTableRecord
#define	AcDbLinetypeTableRecordPointer 	GcDbLinetypeTableRecordPointer
#define	AcDbLoftOptions  	GcDbLoftOptions 
#define	AcDbLongTransWorkSetIterator 	GcDbLongTransWorkSetIterator
#define	AcDbLongTransaction 	GcDbLongTransaction
#define	AcDbMInsertBlock 	GcDbMInsertBlock
#define	AcDbMPolygon 	GcDbMPolygon
#define	AcDbMText 	GcDbMText
#define	AcDbMTextFragment 	GcDbMTextFragment
#define	AcDbMatchProperties 	GcDbMatchProperties
#define	AcDbMaterial 	GcDbMaterial
#define	AcDbMentalRayRenderSettings 	GcDbMentalRayRenderSettings
#define	AcDbMline 	GcDbMline
#define	AcDbMlineStyle 	GcDbMlineStyle
#define	AcDbObject 	GcDbObject
#define	AcDbObjectContextInterface 	GcDbObjectContextInterface
#define	AcDbObjectId 	GcDbObjectId
#define	AcDbObjectIdArray 	GcDbObjectIdArray
#define	AcDbObjectIdGraph 	GcDbObjectIdGraph
#define	AcDbObjectIdGraphNode 	GcDbObjectIdGraphNode
#define	AcDbObjectIterator 	GcDbObjectIterator
#define	AcDbObjectPointer 	GcDbObjectPointer
#define	AcDbObjectPointerBase 	GcDbObjectPointerBase
#define	AcDbObjectReactor 	GcDbObjectReactor
#define	AcDbOle2Frame 	GcDbOle2Frame
#define	AcDbOleFrame 	GcDbOleFrame
#define	AcDbOrdinateDimension 	GcDbOrdinateDimension
#define	AcDbPersistentObjectReactor 	GcDbPersistentObjectReactor
#define	AcDbPlaceHolder 	GcDbPlaceHolder
#define	AcDbPlotSettings 	GcDbPlotSettings
#define	AcDbPlotSettingsValidator 	GcDbPlotSettingsValidator
#define	AcDbPoint 	GcDbPoint
#define	AcDbPolyFaceMesh 	GcDbPolyFaceMesh
#define	AcDbPolyFaceMeshVertex 	GcDbPolyFaceMeshVertex
#define	AcDbPolygonMesh 	GcDbPolygonMesh
#define	AcDbPolygonMeshVertex 	GcDbPolygonMeshVertex
#define	AcDbPolyline 	GcDbPolyline
#define	AcDbProxyEntity 	GcDbProxyEntity
#define	AcDbProxyObject 	GcDbProxyObject
#define	AcDbR13ObjectId 	GcDbR13ObjectId
#define	AcDbRadialDimension 	GcDbRadialDimension
#define	AcDbRasterImage 	GcDbRasterImage
#define	AcDbRasterImageDef 	GcDbRasterImageDef
#define	AcDbRasterImageDefFileAccessReactor 	GcDbRasterImageDefFileAccessReactor
#define	AcDbRasterImageDefReactor 	GcDbRasterImageDefReactor
#define	AcDbRasterImageDefTransReactor 	GcDbRasterImageDefTransReactor
#define	AcDbRasterVariables 	GcDbRasterVariables
#define	AcDbRay 	GcDbRay
#define	AcDbRecover 	GcDbRecover
#define	AcDbRecoverCallBack 	GcDbRecoverCallBack
#define	AcDbRegAppTable 	GcDbRegAppTable
#define	AcDbRegAppTableIterator 	GcDbRegAppTableIterator
#define	AcDbRegAppTablePointer 	GcDbRegAppTablePointer
#define	AcDbRegAppTableRecord 	GcDbRegAppTableRecord
#define	AcDbRegAppTableRecordPointer 	GcDbRegAppTableRecordPointer
#define	AcDbRegion 	GcDbRegion
#define	AcDbRenderEnvironment 	GcDbRenderEnvironment
#define	AcDbRenderGlobal 	GcDbRenderGlobal
#define	AcDbRenderSettings 	GcDbRenderSettings
#define	AcDbRotatedDimension 	GcDbRotatedDimension
#define	AcDbSection 	GcDbSection
#define	AcDbSectionManager 	GcDbSectionManager
#define	AcDbSectionManagerIterator 	GcDbSectionManagerIterator
#define	AcDbSectionSettings 	GcDbSectionSettings
#define	AcDbSequenceEnd 	GcDbSequenceEnd
#define	AcDbServices 	GcDbServices
#define	AcDbShape 	GcDbShape
#define	AcDbSoftOwnershipId 	GcDbSoftOwnershipId
#define	AcDbSoftPointerId 	GcDbSoftPointerId
#define	AcDbSolid 	GcDbSolid
#define	AcDbSortentsTable 	GcDbSortentsTable
#define	AcDbSpatialFilter 	GcDbSpatialFilter
#define	AcDbSpatialIndex 	GcDbSpatialIndex
#define	AcDbSpatialIndexIterator 	GcDbSpatialIndexIterator
#define	AcDbSpline 	GcDbSpline
#define	AcDbStub     	GcDbStub    
#define	AcDbSubentId 	GcDbSubentId
#define	AcDbSummaryInfoManager 	GcDbSummaryInfoManager
#define	AcDbSummaryInfoReactor 	GcDbSummaryInfoReactor
#define	AcDbSymbolTable 	GcDbSymbolTable
#define	AcDbSymbolTableIterator 	GcDbSymbolTableIterator
#define	AcDbSymbolTablePointer 	GcDbSymbolTablePointer
#define	AcDbSymbolTableRecord 	GcDbSymbolTableRecord
#define	AcDbSymbolTableRecordPointer 	GcDbSymbolTableRecordPointer
#define	AcDbTable 	GcDbTable
#define AcCellRange OdCellRange
#define	AcDbTableStyle 	GcDbTableStyle
#define	AcDbText 	GcDbText
#define	AcDbTextStyleTable 	GcDbTextStyleTable
#define	AcDbTextStyleTableIterator 	GcDbTextStyleTableIterator
#define	AcDbTextStyleTablePointer 	GcDbTextStyleTablePointer
#define	AcDbTextStyleTableRecord 	GcDbTextStyleTableRecord
#define	AcDbTextStyleTableRecordPointer 	GcDbTextStyleTableRecordPointer
#define	AcDbTrace 	GcDbTrace
#define	AcDbTransactionManager 	GcDbTransactionManager
#define acdbTransactionManagerPtr gcdbTransactionManagerPtr
#define acdbTransactionManager gcdbTransactionManager
#define	AcDbUCSTable 	GcDbUCSTable
#define	AcDbUCSTableIterator 	GcDbUCSTableIterator
#define	AcDbUCSTablePointer 	GcDbUCSTablePointer
#define	AcDbUCSTableRecord 	GcDbUCSTableRecord
#define	AcDbUCSTableRecordPointer 	GcDbUCSTableRecordPointer
#define	AcDbVertex 	GcDbVertex
#define	AcDbViewTable 	GcDbViewTable
#define	AcDbViewTableIterator 	GcDbViewTableIterator
#define	AcDbViewTablePointer 	GcDbViewTablePointer
#define	AcDbViewTableRecord 	GcDbViewTableRecord
#define	AcDbViewTableRecordPointer 	GcDbViewTableRecordPointer
#define	AcDbViewport 	GcDbViewport
#define	AcDbViewportTable 	GcDbViewportTable
#define	AcDbViewportTableIterator 	GcDbViewportTableIterator
#define	AcDbViewportTablePointer 	GcDbViewportTablePointer
#define	AcDbViewportTableRecord 	GcDbViewportTableRecord
#define	AcDbViewportTableRecordPointer 	GcDbViewportTableRecordPointer
#define	AcDbVisualStyle 	GcDbVisualStyle
#define	AcDbVoidPtrArray 	GcDbVoidPtrArray
#define	AcDbWblockCloneFiler 	GcDbWblockCloneFiler
#define	AcDbWipeout 	GcDbWipeout
#define AcDbSurface   GcDbSurface
#define	AcDbWipeoutVariables 	GcDbWipeoutVariables
#define	AcDbXObject 	GcDbXObject
#define	AcDbXline 	GcDbXline
#define	AcDbXrecord 	GcDbXrecord
#define	AcDbXrecordIterator 	GcDbXrecordIterator
#define	AcDbXrefGraph 	GcDbXrefGraph
#define	AcDbXrefGraphNode 	GcDbXrefGraphNode
#define	AcDbXrefObjectId 	GcDbXrefObjectId
#define AcDbLayerStateManager	GcDbLayerStateManager
#define AcDbColor		GcDbColor
#define AcDbSubDMesh	GcDbSubDMesh
#define AcDbUnderlayReference GcDbUnderlayReference
#define AcDbPdfReference GcDbPdfReference
#define AcDbDwfReference GcDbDwfReference
#define AcDbDgnReference GcDbDgnReference
#define AcDbUnderlayDefinition GcDbUnderlayDefinition
#define AcDbDgnDefinition GcDbDgnDefinition
#define AcDbHelix GcDbHelix
#define AcDbBreakData GcDbBreakData
#define AcDbBreakPointRef GcDbBreakPointRef
#define AcDbRevolveOptions GcDbRevolveOptions
#define AcDbRevolvedSurface GcDbRevolvedSurface
#define AcDbUnderlayHost GcDbUnderlayHost
#define AcDbUnderlayItem GcDbUnderlayItem
#define AcDbUnderlayFile GcDbUnderlayFile
#define AcDbSweepOptions GcDbSweepOptions
#define AcDbPlaneSurface GcDbPlaneSurface
#define AcDbExtrudedSurface GcDbExtrudedSurface
#define AcDbSweptSurface GcDbSweptSurface
#define AcDbNurbSurface GcDbNurbSurface
#define AcDbNurbSurfaceArray GcDbNurbSurfaceArray
#define AcDbLinkedTableData GcDbLinkedTableData
#define AcDbInterferencePE GcDbInterferencePE
#define AcDbPaperOrientationPE GcDbPaperOrientationPE
#define AcDbCamera GcDbCamera
#define AcDMMEntityReactorInfo GcDMMEntityReactorInfo
#define AcDMMEPlotProperties GcDMMEPlotProperties
#define AcDMMEPlotProperty GcDMMEPlotProperty
#define AcDMMEPlotPropertyVec GcDMMEPlotPropertyVec
#define AcDMMNode GcDMMNode
#define AcDMMReactor GcDMMReactor
#define AcDMMResourceInfo GcDMMResourceInfo
#define AcDMMResourceVec GcDMMResourceVec
#define AcDMMSheetReactorInfo GcDMMSheetReactorInfo
#define AcDMMSheetReactorInfo GcDMMSheetReactorInfo
#define AcDMMStringVec GcDMMStringVec
#define AcDMMWideString GcDMMWideString
#define AcDMMXMLAttribute GcDMMXMLAttribute
#define AcDMMXMLAttributeVec GcDMMXMLAttributeVec
#define	AcEdCommand 	GcEdCommand
#define	AcEdCommandIterator 	GcEdCommandIterator
#define	AcEdCommandStack 	GcEdCommandStack
#define	AcEdCommandStruc 	GcEdCommandStruc
#define	AcEdInputContextReactor 	GcEdInputContextReactor
#define	AcEdInputPoint GcEdInputPoint
#define	AcEdInputPointFilter 	GcEdInputPointFilter
#define	AcEdInputPointManager 	GcEdInputPointManager
#define	AcEdInputPointMonitor 	GcEdInputPointMonitor
#define	AcEdInputPointFilterResult GcEdInputPointFilterResult
#define	AcEdInputPointMonitorResult GcEdInputPointMonitorResult
#define	AcEdJig 	GcEdJig
#define	AcEdSSGetFilter 	GcEdSSGetFilter
#define	AcEdSSGetFilter2 	GcEdSSGetFilter2
#define	AcEdSelectionSetService 	GcEdSelectionSetService
#define	AcEdServices 	GcEdServices
#define	AcEdSolidSubentitySelector 	GcEdSolidSubentitySelector
#define	AcEdSymUtilServices 	GcEdSymUtilServices
#define	AcEdUIContext 	GcEdUIContext
#define	AcEdXrefFileLock 	GcEdXrefFileLock
#define	AcEditor 	GcEditor
#define	AcEditorReactor 	GcEditorReactor
#define	AcEditorReactor2 	GcEditorReactor2
#define	AcGe 	GcGe
#define	AcGeAugPolyline3d 	GcGeAugPolyline3d
#define	AcGeBoundBlock2d 	GcGeBoundBlock2d
#define	AcGeBoundBlock3d 	GcGeBoundBlock3d
#define	AcGeBoundedPlane 	GcGeBoundedPlane
#define	AcGeCircArc2d 	GcGeCircArc2d
#define	AcGeCircArc3d 	GcGeCircArc3d
#define	AcGeClipBoundary2d 	GcGeClipBoundary2d
#define	AcGeCompositeCurve2d 	GcGeCompositeCurve2d
#define	AcGeCompositeCurve3d 	GcGeCompositeCurve3d
#define	AcGeCone 	GcGeCone
#define	AcGeContext 	GcGeContext
#define	AcGeCubicSplineCurve2d 	GcGeCubicSplineCurve2d
#define	AcGeCubicSplineCurve3d 	GcGeCubicSplineCurve3d
#define	AcGeCurve2d 	GcGeCurve2d
#define	AcGeCurve3d 	GcGeCurve3d
#define	AcGeCurveBoundary 	GcGeCurveBoundary
#define	AcGeCurveCurveInt2d 	GcGeCurveCurveInt2d
#define	AcGeCurveCurveInt3d 	GcGeCurveCurveInt3d
#define	AcGeCurveSurfInt 	GcGeCurveSurfInt
#define	AcGeCylinder 	GcGeCylinder
#define	AcGeDoubleArray 	GcGeDoubleArray
#define	AcGeDwgIO 	GcGeDwgIO
#define	AcGeDxfIO 	GcGeDxfIO
#define	AcGeEllipArc2d 	GcGeEllipArc2d
#define	AcGeEllipArc3d 	GcGeEllipArc3d
#define	AcGeEntity2d 	GcGeEntity2d
#define	AcGeEntity3d 	GcGeEntity3d
#define	AcGeError 	GcGeError
#define	AcGeExternalBoundedSurface 	GcGeExternalBoundedSurface
#define	AcGeExternalCurve2d 	GcGeExternalCurve2d
#define	AcGeExternalCurve3d 	GcGeExternalCurve3d
#define	AcGeExternalSurface 	GcGeExternalSurface
#define	AcGeFileIO 	GcGeFileIO
#define	AcGeFiler 	GcGeFiler
#define	AcGeIntArray 	GcGeIntArray
#define	AcGeIntersectError 	GcGeIntersectError
#define	AcGeInterval 	GcGeInterval
#define	AcGeKnotVector 	GcGeKnotVector
#define	AcGeLibVersion 	GcGeLibVersion
#define	AcGeLine2d 	GcGeLine2d
#define	AcGeLine3d 	GcGeLine3d
#define	AcGeLineSeg2d 	GcGeLineSeg2d
#define	AcGeLineSeg3d 	GcGeLineSeg3d
#define	AcGeLinearEnt2d 	GcGeLinearEnt2d
#define	AcGeLinearEnt3d 	GcGeLinearEnt3d
#define	AcGeMatrix2d 	GcGeMatrix2d
#define	AcGeMatrix3d 	GcGeMatrix3d
#define	AcGeNurbCurve2d 	GcGeNurbCurve2d
#define	AcGeNurbCurve3d 	GcGeNurbCurve3d
#define	AcGeNurbSurface 	GcGeNurbSurface
#define	AcGeOffsetCurve2d 	GcGeOffsetCurve2d
#define	AcGeOffsetCurve3d 	GcGeOffsetCurve3d
#define	AcGeOffsetSurface 	GcGeOffsetSurface
#define	AcGePlanarEnt 	GcGePlanarEnt
#define	AcGePlane 	GcGePlane
#define	AcGePoint2d 	GcGePoint2d
#define	AcGePoint2dArray 	GcGePoint2dArray
#define	AcGePoint3d 	GcGePoint3d
#define	AcGePoint3dArray 	GcGePoint3dArray
#define	AcGePointEnt2d 	GcGePointEnt2d
#define	AcGePointEnt3d 	GcGePointEnt3d
#define	AcGePointOnCurve2d 	GcGePointOnCurve2d
#define	AcGePointOnCurve3d 	GcGePointOnCurve3d
#define	AcGePointOnSurface 	GcGePointOnSurface
#define	AcGePolyline2d 	GcGePolyline2d
#define	AcGePolyline3d 	GcGePolyline3d
#define	AcGePosition2d 	GcGePosition2d
#define	AcGePosition3d 	GcGePosition3d
#define	AcGeRay2d 	GcGeRay2d
#define	AcGeRay3d 	GcGeRay3d
#define	AcGeScale2d 	GcGeScale2d
#define	AcGeScale3d 	GcGeScale3d
#define	AcGeSphere 	GcGeSphere
#define	AcGeSplineEnt2d 	GcGeSplineEnt2d
#define	AcGeSplineEnt3d 	GcGeSplineEnt3d
#define	AcGeSurfSurfInt 	GcGeSurfSurfInt
#define	AcGeSurface 	GcGeSurface
#define	AcGeTol 	GcGeTol
#define	AcGeTorus 	GcGeTorus
#define	AcGeVector2d 	GcGeVector2d
#define	AcGeVector2dArray 	GcGeVector2dArray
#define	AcGeVector3d 	GcGeVector3d
#define	AcGeVector3dArray 	GcGeVector3dArray
#define	AcGeVoidPointerArray 	GcGeVoidPointerArray
#define	AcGeXConfig 	GcGeXConfig
#define	AcGiCommonDraw 	GcGiCommonDraw
#define	AcGiContext 	GcGiContext
#define	AcGiDrawable 	GcGiDrawable
#define	AcGiDrawableTraits 	GcGiDrawableTraits
#define	AcGiEdgeData 	GcGiEdgeData
#define	AcGiEdgeStyle 	GcGiEdgeStyle
#define	AcGiFaceData 	GcGiFaceData
#define	AcGiFaceStyle 	GcGiFaceStyle
#define	AcGiGeometry 	GcGiGeometry
#define	AcGiGlyph 	GcGiGlyph
#define	AcGiLightAttenuation 	GcGiLightAttenuation
#define	AcGiMapper  	GcGiMapper
#define	AcGiMaterialColor 	GcGiMaterialColor
#define	AcGiMaterialMap  	GcGiMaterialMap
#define	AcGiMaterialTraits 	GcGiMaterialTraits
#define	AcGiMrDiagnosticGridMode 	GcGiMrDiagnosticGridMode
#define	AcGiMrFilter 	GcGiMrFilter
#define	AcGiShadowParameters 	GcGiShadowParameters
#define AcGiShadowParameters2 GcGiShadowParameters2
#define	AcGiSubEntityTraits 	GcGiSubEntityTraits
#define	AcGiTextEngine 	GcGiTextEngine
#define	AcGiTextStyle 	GcGiTextStyle
#define	AcGiVertexData 	GcGiVertexData
#define	AcGiViewport 	GcGiViewport
#define	AcGiViewportDraw 	GcGiViewportDraw
#define	AcGiViewportGeometry 	GcGiViewportGeometry
#define	AcGiVisibility 	GcGiVisibility
#define	AcGiWorldDraw 	GcGiWorldDraw
#define	AcGiWorldGeometry 	GcGiWorldGeometry
#define AcGiPolyline	GcGiPolyline
#define AcGiLineType	GcGiLineType
#define AcGiColorRGB	GcGiColorRGB
#define AcGiColorRGBA   GcGiColorRGBA
#define AcGiPixelBGRA32 GcGiPixelBGRA32
#define AcGiImageBGRA32 GcGiImageBGRA32
#define	AcGs2DViewLimitManager 	GcGs2DViewLimitManager
#define	AcGsClassFactory 	GcGsClassFactory
#define	AcGsColor 	GcGsColor
#define	AcGsConfig 	GcGsConfig
#define	AcGsDCPoint 	GcGsDCPoint
#define	AcGsDCRect 	GcGsDCRect
#define	AcGsDevice 	GcGsDevice
#define	AcGsManager 	GcGsManager
#define	AcGsModel 	GcGsModel
#define	AcGsNode 	GcGsNode
#define	AcGsPath 	GcGsPath
#define	AcGsReactor 	GcGsReactor
#define	AcGsScreenShot 	GcGsScreenShot
#define	AcGsView 	GcGsView
#define	AcLispAppInfo 	GcLispAppInfo
#define	AcLyAndExpr  	GcLyAndExpr
#define	AcLyBoolExpr  	GcLyBoolExpr
#define	AcLyLayerFilter  	GcLyLayerFilter
#define	AcLyLayerFilterManager  	GcLyLayerFilterManager
#define	AcLyLayerGroup  	GcLyLayerGroup
#define	AcLyRelExpr  	GcLyRelExpr
#define AcPlPlotLogger GcPlPlotLogger
#define	AcRxClass 	GcRxClass
#define	AcRxDLinkerReactor 	GcRxDLinkerReactor
#define	AcRxDictionary 	GcRxDictionary
#define	AcRxDictionaryIterator 	GcRxDictionaryIterator
#define	AcRxDynamicLinker 	GcRxDynamicLinker
#define	AcRxEvent 	GcRxEvent
#define	AcRxEventReactor 	GcRxEventReactor
#define	AcRxIterator 	GcRxIterator
#define	AcRxKernel 	GcRxKernel
#define	AcRxObject 	GcRxObject
#define	AcRxService 	GcRxService
#define	AcString 	GcString
#define	AcTransaction 	GcTransaction
#define	AcTransactionManager 	GcTransactionManager
#define	AcTransactionReactor 	GcTransactionReactor
#define	AcadAppInfo 	GcadAppInfo
#define	CAcExtensionModule 	CGcExtensionModule
#define	CAcModuleResourceOverride 	CGcModuleResourceOverride
#define	CAcUiAngleComboBox 	CGcUiAngleComboBox
#define	CAcUiAngleEdit 	CGcUiAngleEdit
#define	CAcUiArrowHeadComboBox 	CGcUiArrowHeadComboBox
#define	CAcUiBitmapButton 	CGcUiBitmapButton
#define	CAcUiBitmapStatic 	CGcUiBitmapStatic
#define	CAcUiColorComboBox 	CGcUiColorComboBox
#define	CAcUiComboBox 	CGcUiComboBox
#define	CAcUiDialog 	CGcUiDialog
#define CAcUiLineTypeComboBox CGcUiLineTypeComboBox
#define	CAcUiDialogBar 	CGcUiDialogBar
#define	CAcUiDockControlBar 	CGcUiDockControlBar
#define	CAcUiDockFrame 	CGcUiDockFrame
#define	CAcUiDropSite 	CGcUiDropSite
#define	CAcUiEdit 	CGcUiEdit
#define	CAcUiFileDialog 	CGcUiFileDialog
#define	CAcUiHeaderCtrl 	CGcUiHeaderCtrl
#define	CAcUiLineWeightComboBox 	CGcUiLineWeightComboBox
#define	CAcUiListBox 	CGcUiListBox
#define	CAcUiListCtrl 	CGcUiListCtrl
#define	CAcUiMRUComboBox 	CGcUiMRUComboBox
#define	CAcUiMRUListBox 	CGcUiMRUListBox
#define	CAcUiNavDialog CGcUiNavDialog
#define	CAcUiNumericComboBox 	CGcUiNumericComboBox
#define	CAcUiNumericEdit 	CGcUiNumericEdit
#define	CAcUiOwnerDrawButton 	CGcUiOwnerDrawButton
#define	CAcUiPickButton 	CGcUiPickButton
#define	CAcUiPlotStyleNamesComboBox 	CGcUiPlotStyleNamesComboBox
#define	CAcUiPlotStyleTablesComboBox 	CGcUiPlotStyleTablesComboBox
#define	CAcUiRegistryAccess 	CGcUiRegistryAccess
#define	CAcUiRegistryDeleteAccess 	CGcUiRegistryDeleteAccess
#define	CAcUiRegistryWriteAccess 	CGcUiRegistryWriteAccess
#define	CAcUiSelectButton 	CGcUiSelectButton
#define	CAcUiString 	CGcUiString
#define	CAcUiStringComboBox 	CGcUiStringComboBox
#define	CAcUiStringEdit 	CGcUiStringEdit
#define	CAcUiSymbolComboBox 	CGcUiSymbolComboBox
#define	CAcUiSymbolEdit 	CGcUiSymbolEdit
#define	CAcUiTab 	CGcUiTab
#define	CAcUiTabChildDialog 	CGcUiTabChildDialog
#define	GetAcadTabPointer GetGcadTabPointer
#define	CAcUiTabExtension 	CGcUiTabExtension
#define	CAcUiTabMainDialog 	CGcUiTabMainDialog
#define	CAcUiToolButton 	CGcUiToolButton
#define	CAcUiTrueColorComboBox 	CGcUiTrueColorComboBox
#define	CAdToolTipCtrl CGdToolTipCtrl
#define	CAdUiBalloonTip 	CGdUiBalloonTip
#define	CAdUiBaseDialog 	CGdUiBaseDialog
#define	CAdUiBitmapButton 	CGdUiBitmapButton
#define	CAdUiBitmapStatic 	CGdUiBitmapStatic
#define	CAdUiComboBox 	CGdUiComboBox
#define	CAdUiDialog 	CGdUiDialog
#define	CAdUiDialogBar 	CGdUiDialogBar
#define	CAdUiDockControlBar 	CGdUiDockControlBar
#define	CAdUiDockFrame 	CGdUiDockFrame
#define	CAdUiDrawTipText 	CGdUiDrawTipText
#define	CAdUiDropSite 	CGdUiDropSite
#define	CAdUiEdit 	CGdUiEdit
#define	CAdUiFileDialog 	CGdUiFileDialog
#define	CAdUiHeaderCtrl 	CGdUiHeaderCtrl
#define	CAdUiListBox 	CGdUiListBox
#define	CAdUiListCtrl 	CGdUiListCtrl
#define	CAdUiOwnerDrawButton 	CGdUiOwnerDrawButton
#define	CAdUiPalette  	CGdUiPalette
#define	CAdUiPaletteSet  	CGdUiPaletteSet
#define	CAdUiRegistryAccess 	CGdUiRegistryAccess
#define	CAdUiRegistryDeleteAccess 	CGdUiRegistryDeleteAccess
#define	CAdUiRegistryWriteAccess 	CGdUiRegistryWriteAccess
#define	CAdUiTab 	CGdUiTab
#define	CAdUiTabChildDialog 	CGdUiTabChildDialog
#define	CAdUiTabExtensionManager 	CGdUiTabExtensionManager
#define	CAdUiTabMainDialog 	CGdUiTabMainDialog
#define	CAdUiTextTip 	CGdUiTextTip
#define	CAdUiTipWindow 	CGdUiTipWindow
#define	CAdUiToolButton 	CGdUiToolButton
#define	CRectangle3d 	GcRectangle3d
#define AcFdFieldEvaluator	GcFdFieldEvaluator
#define AcFdFieldEvaluatorLoader	GcdFdFieldEvaluatorLoader
#define AcFdFieldEngine		GcFdFieldEngine
#define AcFdFieldResult		GcFdFieldResult
#define AcFdFieldValue		GcFieldValue
#define AcFdFieldReactor	GcFdFieldReactor
#define AcGiVisualStyle   GcGiVisualStyle
#define AcGiVisualStyleProperties GcGiVisualStyleProperties
#define AcGiVisualStyleOperations GcGiVisualStyleOperations
#define AcGiVisualStyleTraits GcGiVisualStyleTraits

#define AcDbObjectPointerBase	GcDbObjectPointerBase
#define AcDbObjectPointer	GcDbObjectPointer
#define AcDbDictionaryPointer	GcDbDictionaryPointer
#define AcDbEntityPointer	GcDbEntityPointer

#define AcDbSymbolTablePointer		GcDbSymbolTablePointer
#define AcDbBlockTablePointer		GcDbBlockTablePointer
#define AcDbDimStyleTablePointer	GcDbDimStyleTablePointer
#define AcDbLayerTablePointer		GcDbLayerTablePointer
#define AcDbLinetypeTablePointer	GcDbLinetypeTablePointer
#define AcDbRegAppTablePointer		GcDbRegAppTablePointer
#define AcDbTextStyleTablePointer	GcDbTextStyleTablePointer
#define AcDbUCSTablePointer		GcDbUCSTablePointer
#define AcDbViewTablePointer		GcDbViewTablePointer
#define AcDbViewportTablePointer	GcDbViewportTablePointer

#define AcDbSymbolTableRecordPointer	GcDbSymbolTableRecordPointer
#define AcDbBlockTableRecordPointer	GcDbBlockTableRecordPointer
#define AcDbDimStyleTableRecordPointer	GcDbDimStyleTableRecordPointer
#define AcDbLayerTableRecordPointer	GcDbLayerTableRecordPointer
#define AcDbLinetypeTableRecordPointer	GcDbLinetypeTableRecordPointer
#define AcDbRegAppTableRecordPointer	GcDbRegAppTableRecordPointer
#define AcDbTextStyleTableRecordPointer	GcDbTextStyleTableRecordPointer
#define AcDbUCSTableRecordPointer	GcDbUCSTableRecordPointer
#define AcDbViewTableRecordPointer	GcDbViewTableRecordPointer
#define AcDbViewportTableRecordPointer	GcDbViewportTableRecordPointer

#define AcDbEvalVariant GcDbEvalVariant

#define	AcRxProtocolReactor GcRxProtocolReactor
#define	AcRxProtocolReactorIterator GcRxProtocolReactorIterator
#define	AcRxProtocolReactorList GcRxProtocolReactorList
#define	AcRxProtocolReactorListIterator GcRxProtocolReactorListIterator
#define	AcRxProtocolReactorManager GcRxProtocolReactorManager
#define	AcRxProtocolReactorManagerFactory GcRxProtocolReactorManagerFactory

#define AdApplicationFrame GdApplicationFrame
#define AdMenuBar GdMenuBar

#define AcFILE GcFILE
#define AcCFile GcCFile
#define AcCStdioFile GcCStdioFile
#define AcOutputBufMgr GcOutputBufMgr
#define AdCharFormatter GdCharFormatter

#define acByteSwap gcByteSwap
#define acWriteWCharToCFile gcWriteWCharToCFile
#define acReadCIFFromCFile gcReadCIFFromCFile
#define acReadAnsiCharFromCFile gcReadAnsiCharFromCFile
#define acReadUtf8CharFromCFile gcReadUtf8CharFromCFile
#define acReadUtf16CharFromCFile gcReadUtf16CharFromCFile
#define acCheckCFileCharFormat gcCheckCFileCharFormat

#define AcRxDbxApp GcRxDbxApp
#define AcRxArxApp GcRxArxApp
#define AcDbMLeader GcDbMLeader
#define AcDbMLeaderStyle GcDbMLeaderStyle

#define AcStringArray GcStringArray
#define AcUnderlayLayer GcUnderlayLayer
//}}

//{{Redefine Enum Section
#define	ACUI_ERROR_CODE 	GCUI_ERROR_CODE
#define	ADUI_HT_OPTION_BUTTON 	GDUI_HT_OPTION_BUTTON
#define	ADUI_NOTIFY 	GDUI_NOTIFY
#define	ADUI_REPLY 	GDUI_REPLY
#define	AcDb 	GcDb
#define AcXrefSubCommand GcXrefSubCommand
#define	AcDbDwgVersion 	DwgVersion
#define	AcDbGripOperations 	GcDbGripOperations
#define	AcEdSSGetFlags 	GcEdSSGetFlags
#define	AcEdSSGetModes 	GcEdSSGetModes
#define	AcGiArcType 	GcGiArcType
#define	AcGiColorIntensity 	GcGiColorIntensity
#define	AcGiDeviationType 	GcGiDeviationType
#define	AcGiFillType 	GcGiFillType
#define	AcGiImageOrg 	GcGiImageOrg
#define	AcGiImageOrient 	GcGiImageOrient
#define	AcGiOrientationType 	GcGiOrientationType
#define	AcGiRegenType 	GcGiRegenType
#define	ACRX_X_CALL ODRX_X_CALL
#define	eAcGiRegenTypeInvalid 	eGcGiRegenTypeInvalid
#define	kAcGiArcChord 	kGcGiArcChord
#define	kAcGiArcSector 	kGcGiArcSector
#define	kAcGiArcSimple 	kGcGiArcSimple
#define	kAcGiFillAlways 	kGcGiFillAlways
#define	kAcGiFillNever 	kGcGiFillNever
#define	kAcGiForExplode 	kGcGiForExplode
#define	kAcGiForExtents 	kGcGiForExtents
#define	kAcGiHideOrShadeCommand 	kGcGiHideOrShadeCommand
#define kAcGiShadedDisplay kGcGiShadedDisplay
#define	kAcGiInvisible 	kGcGiInvisible
#define	kAcGiMaxDevForBoundary 	kGcGiMaxDevForBoundary
#define	kAcGiMaxDevForCircle 	kGcGiMaxDevForCircle
#define	kAcGiMaxDevForCurve 	kGcGiMaxDevForCurve
#define	kAcGiMaxDevForFacet 	kGcGiMaxDevForFacet
#define	kAcGiMaxDevForIsoline 	kGcGiMaxDevForIsoline
#define	kAcGiRenderCommand 	kGcGiRenderCommand
#define	kAcGiSaveWorldDrawForProxy 	kGcGiSaveWorldDrawForProxy
#define	kAcGiSaveWorldDrawForR12 	kGcGiForExplode
#define	kAcGiSilhouette 	kGcGiSilhouette
#define	kAcGiStandardDisplay 	kGcGiStandardDisplay
#define	kAcGiVisible 	kGcGiVisible
#define	kAcUiError_Angle 	kGcUiError_Angle
#define	kAcUiError_Blank 	kGcUiError_Blank
#define	kAcUiError_Negative 	kGcUiError_Negative
#define	kAcUiError_None 	kGcUiError_None
#define	kAcUiError_Numeric 	kGcUiError_Numeric
#define	kAcUiError_Range 	kGcUiError_Range
#define	kAcUiError_Symbol 	kGcUiError_Symbol
#define	kAcUiError_Zero 	kGcUiError_Zero
#define	kAcUiMRUCargo_Option1 	kGcUiMRUCargo_Option1
#define	kAcUiMRUCargo_Option2 	kGcUiMRUCargo_Option2
#define	kAcUiMRUCargo_Other1 	kGcUiMRUCargo_Other1
#define	kAdUiNotify_AppMainWindow 	kGdUiNotify_AppMainWindow
#define	kAdUiNotify_AutoLoad 	kGdUiNotify_AutoLoad
#define	kAdUiNotify_Change 	kGdUiNotify_Change
#define	kAdUiNotify_CommandState 	kGdUiNotify_CommandState
#define	kAdUiNotify_DrawTip 	kGdUiNotify_DrawTip
#define	kAdUiNotify_DrawTipText 	kGdUiNotify_DrawTipText
#define	kAdUiNotify_Generic 	kGdUiNotify_Generic
#define	kAdUiNotify_GetTipRect 	kGdUiNotify_GetTipRect
#define	kAdUiNotify_GetTipSupport 	kGdUiNotify_GetTipSupport
#define	kAdUiNotify_GetTipText 	kGdUiNotify_GetTipText
#define	kAdUiNotify_HideWindow 	kGdUiNotify_HideWindow
#define	kAdUiNotify_HitTipRect 	kGdUiNotify_HitTipRect
#define	kAdUiNotify_NotValid 	kGdUiNotify_NotValid
#define	kAdUiNotify_Nothing 	kGdUiNotify_Nothing
#define	kAdUiNotify_Reload 	kGdUiNotify_Reload
#define	kAdUiNotify_RestoreFocus 	kGdUiNotify_RestoreFocus
#define	kAdUiNotify_ShowWindow 	kGdUiNotify_ShowWindow
#define	kAdUiNotify_UpdateTip 	kGdUiNotify_UpdateTip
#define	kAdUiNotify_Valid 	kGdUiNotify_Valid
#define	kAdUiNotify_Validate 	kGdUiNotify_Validate
#define	kAdUiReply_DrawTip 	kGdUiReply_DrawTip
#define	kAdUiReply_NotValid 	kGdUiReply_NotValid
#define	kAdUiReply_Nothing 	kGdUiReply_Nothing
#define	kAdUiReply_Ok 	kGdUiReply_Ok
#define	kAdUiReply_TextTip 	kGdUiReply_TextTip
#define	kAdUiReply_ToolTip 	kGdUiReply_ToolTip
#define	kAdUiReply_Valid 	kGdUiReply_Valid
#define	kOnAutoCADStartup 	kOnDWGdirectStartup
#define	kProd_AcDb 	kProd_GcDb

#define kAcGiWorldPosition 	kGcGiWorldPosition
#define kAcGiViewportPosition 	kGcGiViewportPosition,
#define kAcGiScreenPosition 	kGcGiScreenPosition
#define kAcGiScreenLocalOriginPosition kGcGiScreenLocalOriginPosition
#define kAcGiWorldWithScreenOffsetPosition kGcGiWorldWithScreenOffsetPosition
#define AcGiPositionTransformBehavior GcGiPositionTransformBehavior

#define kAcGiWorldScale 	kGcGiWorldScale    
#define kAcGiViewportScale 	kGcGiViewportScale
#define kAcGiScreenScale 	kGcGiScreenScale
#define kAcGiViewportLocalOriginScale kGcGiViewportLocalOriginScale
#define kAcGiScreenLocalOriginScale kGcGiScreenLocalOriginScale
#define AcGiScaleTransformBehavior GcGiScaleTransformBehavior

#define kAcGiWorldOrientation  kGcGiWorldOrientation
#define kAcGiScreenOrientation kGcGiScreenOrientation
#define kAcGiZAxisOrientation  kGcGiZAxisOrientation
#define AcGiOrientationTransformBehavior GcGiOrientationTransformBehavior
//}}

//{{Redefine Func Section
#define	AcUiMainWindow 	gcedGetGcadFrame
#define	AdUiHideBalloonTip GdUiHideBalloonTip
#define	AdUiShowBalloonTip GdUiShowBalloonTip
#define	AdUiRegisterDockingTool 	GdUiRegisterDockingTool
#define	AdUiSaveDockingToolPositions 	GdUiSaveDockingToolPositions
#define	AdUiShowDockControlBars 	GdUiShowDockControlBars
#define	InitAcUiDLL 	InitGcUiDLL
#define	SetAcadTabPointer 	SetGcadTabPointer
#define	acDocManagerPtr 	gcDocManagerPtr
#define	acTransactionManagerPtr 	gcTransactionManagerPtr
#define	acadErrorStatusText 	gcadErrorStatusText
#define	acapLongTransactionManagerPtr 	gcapLongTransactionManagerPtr
#define	acdbActiveDatabaseArray 	gcdbActiveDatabaseArray
#define	acdbAlloc 	gcad_malloc
#define	acdbAttachXref 	gcdbAttachXref
#define	acdbBindXrefs 	gcdbBindXrefs
#define	acdbCustomOsnapManager 	gcdbCustomOsnapManager
#define	acdbDetachXref 	gcdbDetachXref
#define acdbResolveCurrentXRefs gcdbResolveCurrentXRefs
#define	acdbDisplayPreviewFromDwg 	gcdbDisplayPreviewFromDwg
#define	acdbDwkFileExists 	gcdbDwkFileExists
#define	acdbEcs2Ucs 	gcdbEcs2Ucs
#define	acdbEcs2Wcs 	gcdbEcs2Wcs
#define	acdbFree 	gcad_free
#define	acdbGetAdsName 	gcdbGetGdsName
#define	acdbGetCurVportId 	gcdbGetCurVportId
#define	acdbGetDynDimStyleId 	gcdbGetDynDimStyleId
#define	acdbGetExtnames 	gcdbGetExtnames
#define	acdbGetHostDwgXrefGraph 	gcdbGetHostDwgXrefGraph
#define	acdbGetObjectId 	gcdbGetObjectId
#define	acdbGetPreviewBitmapFromDwg 	gcdbGetPreviewBitmapFromDwg
#define	acdbGetProxyInfo 	gcdbGetProxyInfo
#define	acdbGetReservedString 	gcdbGetReservedString
#define	acdbHostApplicationServices 	gcdbHostApplicationServices
#define	acdbIsPersistentReactor 	gcdbIsPersistentReactor
#define	acdbIsReservedString 	gcdbIsReservedString
#define	acdbLoadLineTypeFile 	gcdbLoadLineTypeFile
#define	acdbOpenAcDbEntity 	gcdbOpenGcDbEntity
#define	acdbOpenAcDbObject 	gcdbOpenGcDbObject
#define	acdbOpenObject 	gcdbOpenObject
#define acdbPostDimAssoc gcdbPostDimAssoc
#define	acdbOverlayXref 	gcdbOverlayXref
#define	acdbPersistentReactorObjectId 	gcdbPersistentReactorObjectId
#define	acdbQueueForRegen 	gcdbQueueForRegen
#define	acdbRealloc 	      gcad_realloc
#define	acdbReleaseHostDwg 	gcdbReleaseHostDwg
#define	acdbReloadXrefs 	gcdbReloadXrefs
#define	acdbSaveAs2000 	gcdbSaveAs2000
#define acdbSaveAs2004 gcdbSaveAs2004
#define acdbSaveAsR14 gcdbSaveAsR14
#define acdbDxfOutAs2004 gcdbDxfOutAs2004
#define acdbDxfOutAs2000 gcdbDxfOutAs2000
#define acdbDxfOutAsR12 gcdbDxfOutAsR12
#define acdbValKey gcdbValKey
#define acdbTextFind gcdbTextFind
#define	acdbSetDbmod 	gcdbSetDbmod
#define	acdbSetExtnames 	gcdbSetExtnames
#define	acdbSymUtil 	gcdbSymUtil
#define	acdbUcs2Ecs 	gcdbUcs2Ecs
#define	acdbUcs2Wcs 	gcdbUcs2Wcs
#define	acdbUcsMatrix 	gcdbUcsMatrix
#define	acdbUnloadXrefs 	gcdbUnloadXrefs
#define	acdbWcs2Ecs 	gcdbWcs2Ecs
#define	acdbWcs2Ucs 	gcdbWcs2Ucs
#define	acdbXBindXrefs 	gcdbXBindXrefs
#define	acdbXlateReservedString 	gcdbXlateReservedString
#define acdbGroupCodeToType		gcdbGroupCodeToType
#define acdbGetRGB	gcdbGetRGB
#define acdbCurDwg	gcdbCurDwg
#define acdbGetCurrentDgnHost gcdbGetCurrentDgnHost
#define acdbConvertHslToRgb gcdbConvertHslToRgb
#define acdbConvertRgbToHsl gcdbConvertRgbToHsl
#define	acedAddDefaultContextMenu 	gcedAddDefaultContextMenu
#define	acedAddObjectContextMenu 	gcedAddObjectContextMenu
#define	acedGetCurDwgXrefGraph 	gcedGetCurDwgXrefGraph
#define	acedGetCurViewportObjectId 	gcedGetCurViewportObjectId
#define	acedGetCurrentSelectionSet 	gcedGetCurrentSelectionSet
#define	acedGetCurrentUCS 	gcedGetCurrentUCS
#define	acedGetIDispatch 	gcedGetIDispatch
#define	acedGetRGB 	gcedGetRGB
#define acedVPLayer  gcedVPLayer
#define	acedIsMenuGroupLoaded 	gcedIsMenuGroupLoaded
#define	acedLoadPartialMenu gcedLoadPartialMenu
#define	acedUnloadPartialMenu gcedUnloadPartialMenu
#define	acedLinetypeDialog   	gcedLinetypeDialog
#define	acedLineWeightDialog  gcedLineWeightDialog
#define	acedNEntSelPEx 	gcedNEntSelPEx
#define	acedPlotstyleDialog gcedPlotstyleDialog
#define	acedPostCommand 	gcedPostCommand
#define	acedPostCommandPrompt 	gcedPostCommandPrompt
#define acedCmdLookup gcedCmdLookup
#define acedCmdLookup2 gcedCmdLookup2
#define acedCmdUndefine gcedCmdUndefine
#define acedPopCommandDirectory gcedPopCommandDirectory
#define acedGetCommandForDocument gcedGetCommandForDocument
#define	acedRemoveDefaultContextMenu 	gcedRemoveDefaultContextMenu
#define	acedRemoveObjectContextMenu 	gcedRemoveObjectContextMenu
#define	acedRestorePreviousUCS 	gcedRestorePreviousUCS
#define	acedSetColorDialog 	gcedSetColorDialog
#define	acedSetColorDialogTrueColor 	gcedSetColorDialogTrueColor
#define	acedSetCurrentUCS 	gcedSetCurrentUCS
#define	acedSetCurrentVPort 	gcedSetCurrentVPort
#define	acedSetCurrentView 	gcedSetCurrentView
#define	acedSyncFileOpen 	gcedSyncFileOpen
#define acedSendModelessOperationStart gcedSendModelessOperationStart
#define acedSendModelessOperationEnded gcedSendModelessOperationEnded
#define	acedUpdateDisplay 	gcedUpdateDisplay
#define	acedVportTableRecords2Vports 	gcedVportTableRecords2Vports
#define	acedVports2VportTableRecords 	gcedVports2VportTableRecords
#define	acedXrefAttach 	gcedXrefAttach
#define	acedXrefBind 	gcedXrefBind
#define	acedXrefCreateBlockname 	gcedXrefCreateBlockname
#define	acedXrefDetach 	gcedXrefDetach
#define	acedXrefOverlay 	gcedXrefOverlay
#define	acedXrefReload 	gcedXrefReload
#define	acedXrefResolve 	gcedXrefResolve
#define	acedXrefUnload 	gcedXrefUnload
#define	acedXrefXBind 	gcedXrefXBind
#define acedEditMTextInteractive gcedEditMTextInteractive
#define AcGlobAddDMMReactor GcGlobAddDMMReactor
#define ACGLOBADDDMMREACTOR GCGLOBADDDMMREACTOR
#define AcGlobRemoveDMMReactor GcGlobRemoveDMMReactor
#define ACGLOBREMOVEDMMREACTOR GCGLOBREMOVEDMMREACTOR
#define acgsGetDisplayInfo gcgsGetDisplayInfo
#define acgsGetViewportInfo gcgsGetViewportInfo
#define acgsGetScreenShot gcgsGetScreenShot
#define acgsSetViewportRenderFlag gcgsSetViewportRenderFlag
#define acgsDisplayImage gcgsDisplayImage
#define acgsRemoveAnonymousGraphics gcgsRemoveAnonymousGraphics
#define acgsSetCustomUpdateMethod gcgsSetCustomUpdateMethod
#define acgsRedrawShortTermGraphics gcgsRedrawShortTermGraphics
#define acgsSetHighlightColor gcgsSetHighlightColor
#define acgsGetHighlightColor gcgsGetHighlightColor
#define acgsSetHighlightLinePattern gcgsSetHighlightLinePattern
#define acgsGetHighlightLinePattern gcgsGetHighlightLinePattern
#define acgsSetHighlightLineWeight gcgsSetHighlightLineWeight
#define acgsGetHighlightLineWeight gcgsGetHighlightLineWeight
#define	acgsSetViewParameters gcgsSetViewParameters
#define acgsGetViewParameters gcgsGetViewParameters
#define acgsSetLensLength gcgsSetLensLength
#define acgsGetLensLength gcgsGetLensLength
#define acgsWriteViewToUndoController gcgsWriteViewToUndoController
#define acgsSetView2D gcgsSetView2D
#define acgsGetGsView gcgsGetGsView
#define	acgsGetGsManager gcgsGetGsManager
#define acgsGetGsModel gcgsGetGsModel
#define acgsGetOrthoViewParameters gcgsGetOrthoViewParameters
#define acgsCreate2DViewLimitManager gcgsCreate2DViewLimitManager
#define acgsDestroy2DViewLimitManager gcgsDestroy2DViewLimitManager
#define acgsDrawableModified gcgsDrawableModified
#define acgsDrawableErased gcgsDrawableErased
#define	aclyGetLayerFilterManager  	gclyGetLayerFilterManager
#define	acrxAppIsLoaded 	gcrxAppIsLoaded
#define	acrxApplicationIsLocked 	gcrxApplicationIsLocked
#define	acrxBuildClassHierarchy 	gcrxBuildClassHierarchy
#define	acrxEntryPoint  	gcrxEntryPoint 
#define	acrxGetServiceSymbolAddr 	gcrxGetServiceSymbolAddr
#define	acrxIsAppMDIAware 	gcrxIsAppMDIAware
#define	acrxLoadApp 	gcrxLoadApp
#define	acrxLoadModule 	gcrxLoadModule
#define	acrxLoadedApps 	gcrxLoadedApps
#define	acrxLockApplication 	gcrxLockApplication
#define	acrxObjectDBXRegistryKey 	gcrxObjectDBXRegistryKey
#define	acrxProductKey 	gcrxProductKey
#define	acrxProductLCID 	gcrxProductLCID
#define	acrxRegisterApp 	gcrxRegisterApp
#define	acrxRegisterAppMDIAware 	gcrxRegisterAppMDIAware
#define	acrxRegisterAppNotMDIAware 	gcrxRegisterAppNotMDIAware
#define	acrxRegisterService 	gcrxRegisterService
#define	acrxServiceIsRegistered 	gcrxServiceIsRegistered
#define	acrxSysRegistry 	gcrxSysRegistry
#define	acrxUnloadApp 	gcrxUnloadApp
#define	acrxUnloadModule 	gcrxUnloadModule
#define	acrxUnlockApplication 	gcrxUnlockApplication
#define	acrxUnregisterApp 	gcrxUnregisterApp
#define	deleteAcRxClass 	deleteGcRxClass
#define	fromAcDbTextStyle 	fromGcDbTextStyle
#define	toAcDbTextStyle 	toGcDbTextStyle
#define acdbAddFieldReactor	gcdbAddFieldReactor
#define acdbRemoveFieldReactor	gcdbRemoveFieldReactor
#define acutAssertMessage gcutAssertMessage
#define acutNewBuffer	gcutNewBuffer
#define acutNewString	gcutNewString
#define acutUpdString	gcutUpdString
#define acutDelString	gcutDelString
#define acutDelBuffer	gcutDelBuffer
#define acdbGetCurVportTableRecordId gcdbGetCurVportTableRecordId
#define acedMspace gcedMspace
#define acedPspace gcedPspace
#define acedGetUnitsValueString gcedGetUnitsValueString
#define acedGetUnitsConversion gcedGetUnitsConversion
#define AcEdDrawOrderCmdType GcEdDrawOrderCmdType
#define acedDrawOrderInherit gcedDrawOrderInherit
#define acdbGetCurViewportObjectId gcdbGetCurViewportObjectId
#define acedViewportIdFromNumber gcedViewportIdFromNumber
#define acedSetColorPrompt gcedSetColorPrompt
#define acdbGetUnitsConversion gcdbGetUnitsConversion
#define acedActiveViewportId gcedActiveViewportId
#define acedSSSubentLength gcedSSSubentLength
#define acedGetFullSubentPathsForCurrentSelection gcedGetFullSubentPathsForCurrentSelection
#define acdbRawAngToF gcdbRawAngToF

#define acdbAcisDeleteModelerBulletins    gcdbAcisDeleteModelerBulletins
#define acdbAcisGetDeleteBulletins        gcdbAcisGetDeleteBulletins
#define acdbModelerStart                  gcdbModelerStart
#define acdbModelerEnd                    gcdbModelerEnd
#define acdbIsModelerStarted              gcdbIsModelerStarted
#define acdbAcisSaveEntityToDwgFiler      gcdbAcisSaveEntityToDwgFiler
#define acdbAcisSaveEntityToDwgFiler2     gcdbAcisSaveEntityToDwgFiler2
#define acdbAcisRestoreEntityFromDwgFiler gcdbAcisRestoreEntityFromDwgFiler
#define acdbAcisSaveEntityToDxfFiler      gcdbAcisSaveEntityToDxfFiler
#define acdbAcisSaveEntityToDxfFiler2     gcdbAcisSaveEntityToDxfFiler2
#define acdbAcisRestoreEntityFromDxfFiler gcdbAcisRestoreEntityFromDxfFiler
#define acdbSetAcisDwgVer                 gcdbSetAcisDwgVer
#define acdbSetCurrentVPort               gcdbSetCurrentVPort
#define acdbAcisDeleteModelerBulletins    gcdbAcisDeleteModelerBulletins

#define AcDbDimAssoc                      GcDbDimAssoc
#define AcDbPointRef                      GcDbPointRef
#define AcDbOsnapPointRef                 GcDbOsnapPointRef
#define IAcReadStream                     IGcReadStream
#define IAcWriteStream                    IGcWriteStream

#define AcDbAnnotativeObjectPE             GcDbAnnotativeObjectPE
#define AcDbArcDimension                   GcDbArcDimension
#define AcDbRadialDimensionLarge           GcDbRadialDimensionLarge
#define AcDbLayerStateManagerReactor       GcDbLayerStateManagerReactor
#define AcApStatusBar                      GcApStatusBar
#define AcStatusBarItem                    GcStatusBarItem
#define AcStatusBarMenuItem                GcStatusBarMenuItem
#define AcPane                             GcPane
#define AcDefaultPane                      GcDefaultPane
#define AcStatusBarType                    GcStatusBarType
#define AcTrayItem                         GcTrayItem
#define AcTrayItemAnimationControl         GcTrayItemAnimationControl
#define AcTrayItemAnimationCallbackFunc    GcTrayItemAnimationCallbackFunc
#define AcTrayItemAnimationCallbackData    GcTrayItemAnimationCallbackData
#define AcTrayItemBubbleWindowControl      GcTrayItemBubbleWindowControl
#define AcTrayItemBubbleWindowCallbackFunc GcTrayItemBubbleWindowCallbackFunc
#define AcTrayItemBubbleWindowCallbackData GcTrayItemBubbleWindowCallbackData
#define acedGetAcadDoc                    gcedGetGcadDoc
#define acedGetAcadDwgView                gcedGetGcadDwgView
#define acedGetAcadFrame                  gcedGetGcadFrame
#define acedGetAcadDockCmdLine            gcedGetGcadDockCmdLine
#define acedGetAcadTextCmdLine            gcedGetGcadTextCmdLine
#define acedGetAcadResourceInstance       gcedGetGcadResourceInstance
#define acedDwgPoint                      gcedDwgPoint
#define acedCoordFromPixelToWorld         gcedCoordFromPixelToWorld
#define acedCoordFromPixelToWorld         gcedCoordFromPixelToWorld
#define acedCoordFromWorldToPixel         gcedCoordFromWorldToPixel
#define acedGetWinNum                     gcedGetWinNum
#define acedSetStatusBarProgressMeter     gcedSetStatusBarProgressMeter
#define acedSetStatusBarProgressMeterPos  gcedSetStatusBarProgressMeterPos
#define acedRestoreStatusBar              gcedRestoreStatusBar
#define AcedWatchWinMsgFn                 GcedWatchWinMsgFn
#define AcedFilterWinMsgFn                GcedFilterWinMsgFn
#define AcedOnIdleMsgFn                   gcedOnIdleMsgFn
#define acedRegisterFilterWinMsg          gcedRegisterFilterWinMsg
#define acedRemoveFilterWinMsg		        gcedRemoveFilterWinMsg
#define acedRegisterWatchWinMsg		        gcedRegisterWatchWinMsg
#define acedRemoveWatchWinMsg             gcedRemoveWatchWinMsg
#define acedRegisterOnIdleWinMsg          gcedRegisterOnIdleWinMsg
#define acedRemoveOnIdleWinMsg            gcedRemoveOnIdleWinMsg
#define AcColorSettings                   GcColorSettings
#define acedGetCurrentColors              gcedGetCurrentColors
#define acedSetCurrentColors              gcedSetCurrentColors
#define acedGetSystemColors               gcedGetSystemColors  
#define AcChildFrmSettings                gcChildFrmSettings
#define acedGetChildFrameSettings         gcedGetChildFrameSettings
#define acedSetChildFrameSettings         gcedSetChildFrameSettings
#define acedRegisterCustomDropTarget      gcedRegisterCustomDropTarget
#define acedStartOverrideDropTarget       gcedStartOverrideDropTarget
#define acedRevokeCustomDropTarget        gcedRevokeCustomDropTarget
#define acedEndOverrideDropTarget         gcedEndOverrideDropTarget
#define acedAddDropTarget                 gcedAddDropTarget
#define acedRemoveDropTarget              gcedRemoveDropTarget
#define AcApGetDatabase                   GcApGetDatabase
#define acedGetRegistryCompany            gcedGetRegistryCompany
#define acedRegisterExtendedTab           gcedRegisterExtendedTab
#define acedGetMenu                       gcedGetMenu
#define acedIsInputPending                gcedIsInputPending
#define acedSetIUnknownForCurrentCommand  gcedSetIUnknownForCurrentCommand
#define acedGetIUnknownForCurrentCommand  gcedGetIUnknownForCurrentCommand
#define acedGetApplicationStatusBar       gcedGetApplicationStatusBar
#define acedShowDrawingStatusBars         gcedShowDrawingStatusBars
#define acedDrawingStatusBarsVisible      gcedDrawingStatusBarsVisible
#define acedRegisterStatusBarMenuItem     gcedRegisterStatusBarMenuItem
#define acedUnregisterStatusBarMenuItem   gcedUnregisterStatusBarMenuItem
#define acedSetStatusBarPaneID            gcedSetStatusBarPaneID
#define AcColorSettingsEx                 GcColorSettingsEx
#define acedGetCurrentColorsEx            gcedGetCurrentColorsEx
#define acedSetCurrentColorsEx            gcedSetCurrentColorsEx
#define acedGetSystemColorsEx             gcedGetSystemColorsEx
#define accmGetColorFromACIName		  gccmGetColorFromACIName
#define accmGetColorFromRGBName		  gccmGetColorFromRGBName
#define accmGetColorFromColorBookName     gccmGetColorFromColorBookName
#define accmGetLocalizedColorNames	  gccmGetLocalizedColorNames	
#define acedEditToleranceInteractive  gcedEditToleranceInteractive
//}}

//{{Redefine Macro Section
#define	ACDB_DECLARE_MEMBERS 	GCDB_DECLARE_MEMBERS
#define	ACRX_CLASS_DICTIONARY 	GCRX_CLASS_DICTIONARY
#define	ACRX_CMD_DEFUN 	GcEdCommand::kDefun
#define	ACRX_CMD_DOCEXCLUSIVELOCK 	GcEdCommand::kDocExclusiveLock
#define	ACRX_CMD_DOCREADLOCK 	GcEdCommand::kDocReadLock
#define	ACRX_CMD_INPROGRESS 	GcEdCommand::kInProgress
#define	ACRX_CMD_INTERRUPTIBLE 	GcEdCommand::kInterruptible
#define	ACRX_CMD_MODAL 	GcEdCommand::kModal
#define	ACRX_CMD_NOBEDIT 	GcEdCommand::kNoBedit
#define	ACRX_CMD_NOHISTORY 	GcEdCommand::kNoHistory
#define	ACRX_CMD_NOINTERNALLOCK 	GcEdCommand::kNoInternalLock
#define	ACRX_CMD_NOMULTIPLE 	GcEdCommand::kNoMultiple
#define	ACRX_CMD_NONEWSTACK 	GcEdCommand::kNoNewStack
#define	ACRX_CMD_NOOEM 	GcEdCommand::kNoOEM
#define	ACRX_CMD_NOPAPERSPACE 	GcEdCommand::kNoPaperspace
#define	ACRX_CMD_NOPERSPECTIVE 	GcEdCommand::kNoPerspective
#define	ACRX_CMD_NOTILEMODE 	GcEdCommand::kNoTilemode
#define	ACRX_CMD_NO_UNDO_MARKER 	GcEdCommand::kNoUndoMarker
#define	ACRX_CMD_PLOTONLY 	GcEdCommand::kPlotOnly
#define	ACRX_CMD_REDRAW 	GcEdCommand::kRedraw
#define	ACRX_CMD_SESSION 	GcEdCommand::kSession
#define	ACRX_CMD_TRANSPARENT 	GcEdCommand::kTransparent
#define	ACRX_CMD_UNDEFINED 	GcEdCommand::kUndefined
#define	ACRX_CMD_USEPICKSET 	GcEdCommand::kUsePickset
#define ACRX_CMD_LISPASCMD GcEdCommand::kLispAsCmd
#define	ACRX_CONS_DEFINE_MEMBERS 	GCRX_CONS_DEFINE_MEMBERS
#define ACRX_DEFINE_MEMBERS(ClassName) GCRX_CONS_DEFINE_MEMBERS(ClassName,AcRxObject,0)
#define	ACRX_DECLARE_MEMBERS 	GCRX_DECLARE_MEMBERS
#define	ACRX_DXF_DEFINE_MEMBERS 	GCRX_DXF_DEFINE_MEMBERS
#define	ACRX_EVENT_OBJ 	GCRX_EVENT_OBJ
#define	ACRX_NO_CONS_DEFINE_MEMBERS 	GCRX_NO_CONS_DEFINE_MEMBERS
#define	ACRX_NO_CONS_DEFINE_MEMBERS_TEMPLARG 	GCRX_NO_CONS_DEFINE_MEMBERS_TEMPLARG
#define	ACRX_PROTOCOL_REACTOR_MANAGER_AT GCRX_PROTOCOL_REACTOR_MANAGER_AT
#define	ACRX_PROTOCOL_REACTOR_LIST_AT GCRX_PROTOCOL_REACTOR_LIST_AT
#define	AC_DECLARE_EXTENSION_MODULE 	GC_DECLARE_EXTENSION_MODULE
#define	AC_IMPLEMENT_EXTENSION_MODULE 	GC_IMPLEMENT_EXTENSION_MODULE
#define IMPLEMENT_ARX_ENTRYPOINT IMPLEMENT_GRX_ENTRYPOINT
#define ACDB_INFINITE_XCLIP_DEPTH GCDB_INFINITE_XCLIP_DEPTH
//#define ACDB_ANNOTATIONSCALES_COLLECTION GCDB_ANNOTATIONSCALES_COLLECTION
#define	ADESK_NO_VTABLE 	HCCAD_NO_VTABLE
#define	ADESK_STDCALL 	HCCAD_STDCALL
#define ACRX_PE_PTR     GCRX_PE_PTR
#define AC_SRCH_BLOCK GC_SRCH_BLOCK
#define AC_SRCH_DIM_TEXT   GC_SRCH_DIM_TEXT
#define AC_SRCH_TEXT       GC_SRCH_TEXT
#define AC_SRCH_LINK_DESC  GC_SRCH_LINK_DESC
#define AC_SRCH_LINK_URL   GC_SRCH_LINK_URL
#define AC_SRCH_MATCH_CASE GC_SRCH_MATCH_CASE
#define AC_SRCH_WHOLE_WORD GC_SRCH_WHOLE_WORD
#define AC_SRCH_DEFAULT    GC_SRCH_DEFAULT
#define ACSB_NOBORDERS  GCSB_NOBORDERS
#define ACSB_INACTIVE  GCSB_INACTIVE
#define ACSB_STRETCH  GCSB_STRETCH
#define ACSB_ACTIVE  GCSB_ACTIVE
#define ACSB_COMMAND  GCSB_COMMAND
#define ACSB_POPUP  GCSB_POPUP
#define ACSB_POPOUT  GCSB_POPOUT 
#define ACSB_NORMAL  GCSB_NORMAL
#define ACSBPANE_APP_MODEMACRO  GCSBPANE_APP_MODEMACRO
#define ACSBPANE_APP_CURSORCOORD  GCSBPANE_APP_CURSORCOORD
#define ACSBPANE_APP_SNAP  GCSBPANE_APP_SNAP
#define ACSBPANE_APP_GRID  GCSBPANE_APP_GRID
#define ACSBPANE_APP_ORTHO  GCSBPANE_APP_ORTHO
#define ACSBPANE_APP_POLAR  GCSBPANE_APP_POLAR
#define ACSBPANE_APP_OTRACK  GCSBPANE_APP_OTRACK
#define ACSBPANE_APP_LINEWEIGHT  GCSBPANE_APP_LINEWEIGHT
#define ACSBPANE_APP_PAPERMODEL  GCSBPANE_APP_PAPERMODEL
#define ACSBPANE_APP_PAPER  GCSBPANE_APP_PAPER
#define ACSBPANE_APP_MODEL  GCSBPANE_APP_MODEL
#define ACSBPANE_APP_OSNAP  GCSBPANE_APP_OSNAP
#define ACSBPANE_APP_FLOAT  GCSBPANE_APP_FLOAT
#define ACSBPANE_APP_TABLET  GCSBPANE_APP_TABLET
#define ACSBPANE_APP_SPACER  GCSBPANE_APP_SPACER
#define ACSBPANE_APP_VPMAX_PREV  GCSBPANE_APP_VPMAX_PREV
#define ACSBPANE_APP_VPMAX  GCSBPANE_APP_VPMAX
#define ACSBPANE_APP_VPMAX_NEXT  GCSBPANE_APP_VPMAX_NEXT
#define ACSBPANE_APP_DYNINPUT  GCSBPANE_APP_DYNINPUT
#define ACSBPANE_APP_DYNAMICUCS  GCSBPANE_APP_DYNAMICUCS
#define ACSBPANE_APP_LAYOUTMODELICONS  GCSBPANE_APP_LAYOUTMODELICONS
#define ACSBPANE_APP_MODEL_ICON  GCSBPANE_APP_MODEL_ICON
#define ACSBPANE_APP_LAYOUT_ICON  GCSBPANE_APP_LAYOUT_ICON
#define ACSBPANE_APP_LAYOUTMORE_ICON  GCSBPANE_APP_LAYOUTMORE_ICON
#define ACSBPANE_APP_ALL  GCSBPANE_APP_ALL
#define ACSBPANE_ANNO_STRETCH  GCSBPANE_ANNO_STRETCH
#define ACSBPANE_ANNO_AUTOSCALE  GCSBPANE_ANNO_AUTOSCALE
#define ACSBPANE_ANNO_VIEWPORT_SCALE_LABEL  GCSBPANE_ANNO_VIEWPORT_SCALE_LABEL
#define ACSBPANE_ANNO_VIEWPORT_SCALE  GCSBPANE_ANNO_VIEWPORT_SCALE
#define ACSBPANE_ANNO_VIEWPORT_LOCK_STATE  GCSBPANE_ANNO_VIEWPORT_LOCK_STATE
#define ACSBPANE_ANNO_ANNOTATION_SCALE_LABEL  GCSBPANE_ANNO_ANNOTATION_SCALE_LABEL
#define ACSBPANE_ANNO_ANNOTATION_SCALE  GCSBPANE_ANNO_ANNOTATION_SCALE
#define ACSBPANE_ANNO_ANNO_ALL_VISIBLE  GCSBPANE_ANNO_ANNO_ALL_VISIBLE
#define ACSBPANE_ANNO_EMPTY  GCSBPANE_ANNO_EMPTY
#define ACSBPANE_APP_STRETCH  GCSBPANE_APP_STRETCH
#define ACSBPANE_APP_WORKSPACE  GCSBPANE_APP_WORKSPACE
#define ACSBPANE_APP_WORKSPACE_LOCK  GCSBPANE_APP_WORKSPACE_LOCK
#define ACSBPANE_APP_QPROPERTIES  GCSBPANE_APP_QPROPERTIES
#define ACSBPANE_ANNO_SYNCHSCALES  GCSBPANE_ANNO_SYNCHSCALES
#define ACSBPANE_APP_QV_LAYOUTS  GCSBPANE_APP_QV_LAYOUTS
#define ACSBPANE_APP_QV_DRAWINGS  GCSBPANE_APP_QV_DRAWINGS
#define ACSBPANE_APP_QV_SPACER  GCSBPANE_APP_QV_SPACER         
#define ACSBPANE_APP_QV_PAN  GCSBPANE_APP_QV_PAN     
#define ACSBPANE_APP_QV_ZOOM  GCSBPANE_APP_QV_ZOOM    
#define ACSBPANE_APP_QV_STEERINGWHEEL  GCSBPANE_APP_QV_STEERINGWHEEL
#define ACSBPANE_APP_QV_SHOWMOTION  GCSBPANE_APP_QV_SHOWMOTION
#define ACSBPANE_APP_QV_ANNO_SPACER  GCSBPANE_APP_QV_ANNO_SPACER
#define ACSBPANE_APP_3DOSNAP  GCSBPANE_APP_3DOSNAP
#define ACSBPANE_APP_WORKSPACE_PERFORMANCE  GCSBPANE_APP_WORKSPACE_PERFORMANCE
#define ACSBPANE_APP_SELECTIONCYCLING  GCSBPANE_APP_SELECTIONCYCLING
#define ACSBPANE_APP_TRANSPARENCY  GCSBPANE_APP_TRANSPARENCY
#define ACSBPANE_APP_INFER  GCSBPANE_APP_INFER
#define	AcRxFunctionPtr 	GcRxFunctionPtr
#define	acDocManager 	gcDocManager
#define	acapLongTransactionManager 	gcapLongTransactionManager
#define	acedEditor 	  gcedEditor
#define	acedRegCmds 	gcedRegCmds
#define	acProfileManagerPtr gcProfileManagerPtr
#define	acrxClassDictionary 	gcrxClassDictionary
#define	acrxDynamicLinker 	gcrxDynamicLinker
#define	acrxEvent 	gcrxEvent
#define	acrxProtocolReactors gcrxProtocolReactors
#define	acrxServiceDictionary 	gcrxServiceDictionary
#define	actrTransactionManager 	gctrTransactionManager
#define WM_ACAD_KEEPFOCUS	WM_GCAD_KEEPFOCUS
//}}

//{{Redefine Member Section
//}}

//{{Redefine Method Section
#define	DoAdUiMessage 	DoGdUiMessage
#define	addAcDbObject 	addGcDbObject
#define	appendAcDbEntity 	appendGcDbEntity
#define	createAutoCADDevice 	createCADDevice
#define	createAutoCADModel 	createCADModel
#define	createAutoCADView 	createCADView
#define	createAutoCADViewport 	createCADViewport
#define	destroyAutoCADDevice 	destroyCADDevice
#define	destroyAutoCADModel 	destroyCADModel
#define	destroyAutoCADView 	destroyCADView
#define	getAcDbHandle 	getGcDbHandle
#define	getAcDbObjectId 	getGcDbObjectId
#define	readAcDbHandle 	readGcDbHandle
#define	setAcDbObjectIdsInFlux 	setGcDbObjectIdsInFlux
#define	treatAsAcDbBlockRefForExplode 	treatAsGcDbBlockRefForExplode
#define	writeAcDbHandle 	writeGcDbHandle
//}}

#define acdbGetSummaryInfo gcdbGetSummaryInfo

//{{Redefine Struct Section
#define	AcAp 	GcAp
#define	AcDbSymUtilServices 	GcDbSymUtilServices
#define	AcDbSymbolUtilities 	GcDbSymbolUtilities
#define AcDbSymUtil 		GcDbSymUtil 
#define	AcGiClipBoundary 	GcGiClipBoundary
#define	AcGiRequestScanLines 	GcGiRequestScanLines
#define	AcGiSentScanLines 	GcGiSentScanLines
#define	AcGsClientViewInfo 	GcGsClientViewInfo
#define	AcRx 	GcRx
#define	Acad 	Gcad
#define	AcadApp 	GcadApp
#define	Adesk 	Hccad
#define ACHAR	GCHAR
#define _ACRX_T _GCRX_T
#define ACRX_T GCRX_T
#define AdInt32 HcInt32
//}}

//{{ºØ≥…ÃÌº”

#define AcDbHomeView GcDbHomeView
#define acedSSSetSubentTypes gcedSSSetSubentTypes
#define AcDbDwfDefinition GcDbDwfDefinition
#define AcEdSSGetFilter GcEdSSGetFilter
#define AcEdSSGet GcEdSSGet
#define AcDbAnnotationScale GcDbAnnotationScale
#define AcDbObjectContext GcDbObjectContext
#define AcDbObjectContextManager GcDbObjectContextManager
#define AcDbObjectContextCollection GcDbObjectContextCollection
#define AcDbObjectContextCollectionIterator GcDbObjectContextCollectionIterator
#define AcDbTableContent GcDbTableContent
#define AcDbTableTemplate GcDbTableTemplate
#define AcValue GcValue
#define acdbGetCurUserViewportId gcdbGetCurUserViewportId
#define acedSSSubentName gcedSSSubentName
#define acedSSSubentNameX gcedSSSubentNameX
#define AcDbPdfDefinition GcDbPdfDefinition
#define acdbGetCurrentDwfHost gcdbGetCurrentDwfHost
#define acdbGetSummaryInfo gcdbGetSummaryInfo
#define acdbPutSummaryInfo gcdbPutSummaryInfo
#define AcEdSSGetFilter4 GcEdSSGetFilter4
#define AcDbHandleArrayPtRef GcDbHandleArrayPtRef
#define AcDbHomeView GcDbHomeView
#define AcGiVariant GcGiVariant
#define acdbSetHomeView gcdbSetHomeView
#define acdbGetHomeView gcdbGetHomeView
#define acdbSetShowCompass gcdbSetShowCompass
#define acdbGetShowCompass gcdbGetShowCompass
#define CAdUiSearchBox CGdUiSearchBox
#define AcDbLoftedSurface GcDbLoftedSurface 
#define CAcUiPredefBlockComboBox CGcUiPredefBlockComboBox
#define acedInitCommandVersion gcedInitCommandVersion
#define acedInitDialog gcedInitDialog
#define acdbGetViewportVisualStyle gcdbGetViewportVisualStyle
#define acdbSetViewportVisualStyle gcdbSetViewportVisualStyle
#define acedEatCommandThroat gcedEatCommandThroat
#define acedIsUpdateDisplayPaused gcedIsUpdateDisplayPaused
#define acedUpdateDisplayPause gcedUpdateDisplayPause
#define acdbLoadMlineStyleFile gcdbLoadMlineStyleFile 
// data styles
#define AC_ES_STRING GC_ES_STRING	
#define	AC_ES_SYMBOL GC_ES_SYMBOL 
#define AC_ES_NUMERIC GC_ES_NUMERIC 
#define AC_ES_ANGLE GC_ES_ANGLE 

// behavior styles
#define AC_ES_VAL_ONKILLFOCUS  GC_ES_VAL_ONKILLFOCUS
#define AC_ES_CONV_ONKILLFOCUS GC_ES_CONV_ONKILLFOCUS
#define AC_ES_SHOW_ERRMSG GC_ES_SHOW_ERRMSG
#define AC_ES_ERRMSG_ALLOWIGNORE GC_ES_ERRMSG_ALLOWIGNORE

// validation styles
#define AC_ES_NOZERO GC_ES_NOZERO
#define AC_ES_NOBLANK	 GC_ES_NOBLANK
#define AC_ES_NONEGATIVE GC_ES_NONEGATIVE
#define	AC_ES_INRANGE GC_ES_INRANGE

//}}
#define NULLCB GDS_NULLCB
#define CBR_SELECT GDS_CBR_SELECT
#define CBR_LOST_FOCUS GDS_CBR_LOST_FOCUS
#define CBR_DRAG GDS_CBR_DRAG
#define CBR_DOUBLE_CLICK GDS_CBR_DOUBLE_CLICK

#define DLGALLDONE GDS_DLGALLDONE
#define DLGCANCEL GDS_DLGCANCEL
#define DLGOK GDS_DLGOK
#define DLGSTATUS GDS_DLGSTATUS

#define LIST_CHANGE GDS_LIST_CHANGE
#define LIST_APPEND GDS_LIST_APPEND
#define LIST_NEW GDS_LIST_NEW

#define MODE_ENABLE GDS_MODE_ENABLE
#define MODE_DISABLE GDS_MODE_DISABLE
#define MODE_SETFOCUS GDS_MODE_SETFOCUS
#define MODE_SETSEL GDS_MODE_SETSEL
#define MODE_FLIP GDS_MODE_FLIP

#define MAX_TILE_STR GDS_MAX_TILE_STR
#define TILE_STR_LIMIT GDS_TILE_STR_LIMIT

#define BAD_DIALOG GDS_BAD_DIALOG

#define BGLCOLOR GDS_BGLCOLOR
#define DBGLCOLOR GDS_DBGLCOLOR
#define DFGLCOLOR GDS_DFGLCOLOR
#define LINELCOLOR GDS_LINELCOLOR

#define AcFileDependencyInfo GcFileDependencyInfo
#define AcFileDependencyManager GcFileDependencyManager
#define AcDbIndexFilterManager GcDbIndexFilterManager
#define AcDmUtil GcDmUtil

//{{
#define AcApProfileManager 		GcApProfileManager
#define acdbOriginalXrefFullPathFor 	gcdbOriginalXrefFullPathFor
#define AdUiTitleBarLocationnLocationOri  		GdUiTitleBarLocationnLocationOri 
#define AdUiTitleBarLocation  		GdUiTitleBarLocation

#define CAdUiPatetteset					CGdUiPaletteSet
//}}

//{{aduiDock.h
#define ADUI_DOCK_POSITION_TOOL_KEY     GCUI_DOCK_POSITION_TOOL_KEY
#define ADUI_DOCK_STARTUP_TOOL_KEY      GDUI_DOCK_STARTUP_TOOL_KEY
#define ADUI_XML_ROOT                   GDUI_XML_ROOT
#define ADUI_XML_DOCK_TOOL_INFO         GDUI_XML_DOCK_TOOL_INFO
#define ADUI_XML_DOCK_TOOL              GDUI_XML_DOCK_TOOL
#define ADUI_XML_DOCK_TOOL_CLSID        GDUI_XML_DOCK_TOOL_CLSID
#define ADUI_XML_DOCK_STARTUP_INFO      GDUI_XML_DOCK_STARTUP_INFO
#define ADUI_XML_DOCK_STARTUP_TOOL_NAME GDUI_XML_DOCK_STARTUP_TOOL_NAME
#define ADUI_XML_DOCK_STARTUP_CMD_NAME  GDUI_XML_DOCK_STARTUP_CMD_NAME
#define ID_ADUI_ALLOWDOCK          	GD_GDUI_ALLOWDOCK
#define ID_ADUI_HIDEBAR             	GD_GDUI_HIDEBAR
#define ADUI_DOCK_CS_DESTROY_ON_CLOSE  	GDUI_DOCK_CS_DESTROY_ON_CLOSE  
#define ADUI_DOCK_CS_STDMOUSECLICKS    	GDUI_DOCK_CS_STDMOUSECLICKS   
#define ADUI_DOCK_NF_SIZECHANGED       	GDUI_DOCK_NF_SIZECHANGED
#define ADUI_DOCK_NF_STATECHANGED      	GDUI_DOCK_NF_STATECHANGED
#define ADUI_DOCK_NF_FRAMECHANGED      	GDUI_DOCK_NF_FRAMECHANGED
//}}

//{{redefine Constraints
#define AcDbAssocAction GcDbAssocAction
#define AcDbAssocStatus GcDbAssocStatus
#define AcDbAssocNetwork GcDbAssocNetwork 
#define AcDbAssoc2dConstraintGroup GcDbAssoc2dConstraintGroup 
#define AcConstrainedGeometry GcConstrainedGeometry 
#define AcGeomConstraint	GcGeomConstraint	  
#define AcDbAssocManager	GcDbAssocManager	
#define AcConstraintGroupNodeId	GcConstraintGroupNodeId	
#define AcDbAssocDependency GcDbAssocDependency 
#define AcDbAssocGeomDependency	GcDbAssocGeomDependency	
#define AcConstrainedImplicitPoint	GcConstrainedImplicitPoint	
#define AcTangentConstraint		GcTangentConstraint		
#define AcColinearConstraint	GcColinearConstraint	
#define AcCenterPointConstraint	GcCenterPointConstraint	
#define AcConcentricConstraint  GcConcentricConstraint  
#define AcG2SmoothConstraint	GcG2SmoothConstraint	
#define AcCompositeConstraint	GcCompositeConstraint	
#define AcEqualCurvatureConstraint	GcEqualCurvatureConstraint	
#define AcEqualDistanceConstraint	GcEqualDistanceConstraint	
#define AcEqualLengthConstraint		GcEqualLengthConstraint		
#define AcFixedConstraint			GcFixedConstraint			
#define AcNormalConstraint			GcNormalConstraint			
#define AcHorizontalConstraint		GcHorizontalConstraint		
#define AcVerticalConstraint		GcVerticalConstraint		
#define AcParallelConstraint		GcParallelConstraint		
#define AcPerpendicularConstraint	GcPerpendicularConstraint	
#define AcPointCoincidenceConstraint	GcPointCoincidenceConstraint	
#define AcSymmetricConstraint	GcSymmetricConstraint	
#define AcEqualHelpParameterConstraint	GcEqualHelpParameterConstraint	
#define AcExplicitConstraint	GcExplicitConstraint	
#define AcEqualRadiusConstraint	GcEqualRadiusConstraint	
#define AcPointCurveConstraint	GcPointCurveConstraint	
#define AcConstrainedCircle		GcConstrainedCircle		
#define AcConstrainedEllipse	GcConstrainedEllipse	
#define AcConstrainedLine		GcConstrainedLine		
#define AcConstrainedPoint		GcConstrainedPoint		
#define AcConstrainedSpline		GcConstrainedSpline		
#define AcConstrainedCurve		GcConstrainedCurve		
#define AcConstrainedRigidSet	GcConstrainedRigidSet	
#define AcDbAssocPersSubentIdPE	GcDbAssocPersSubentIdPE	
#define AcDbAssocVariable		GcDbAssocVariable		
#define AcDbAssocValueDependency	GcDbAssocValueDependency	
#define AcDbAssocDimDependencyBody	GcDbAssocDimDependencyBody	
#define AcDistanceConstraint		GcDistanceConstraint		
#define AcDbCompoundObjectId		GcDbCompoundObjectId		
#define AcAngleConstraint			GcAngleConstraint			
#define Ac3PointAngleConstraint		Gc3PointAngleConstraint	
#define AcDbAssocActionBody GcDbAssocActionBody
#define AcDbAssocParamBasedActionBody GcDbAssocParamBasedActionBody
#define AcDbAssocArrayActionBody  GcDbAssocArrayActionBody
#define AcDbAssocArrayParameters GcDbAssocArrayParameters
#define AcDbItemLocator GcDbItemLocator
#define AcDbAssocActionParam GcDbAssocActionParam
#define AcDbGeomRef GcDbGeomRef
#define AcDbAssocArrayPathParameters GcDbAssocArrayPathParameters
#define AcDbAssocArrayPolarParameters GcDbAssocArrayPolarParameters
#define AcDbAssocArrayRectangularParameters GcDbAssocArrayRectangularParameters
#define AcDbAssocArrayCommonParameters GcDbAssocArrayCommonParameters
#define AcDbVertexRef                  GcDbVertexRef
//}}


#define AcDbModelDocViewStyle GcDbModelDocViewStyle
#define AcDbDetailViewStyle   GcDbDetailViewStyle
#define AcDbSectionViewStyle  GcDbSectionViewStyle

//{{redefine PointCloud
#define AcDbPointCloud        	GcDbPointCloud
#define AcDbPointCloudDef	GcDbPointCloudDef
#define AcDbPointCloudEx	GcDbPointCloudEx
#define AcDbPointCloudDefEx	GcDbPointCloudDefEx
#define AcDbPointCloudCrop	GcDbPointCloudCrop	
#define AcDbPointCloudColorMap	GcDbPointCloudColorMap	
//}}

#define AcPlDSDEntries                GcPlDSDEntries
#define AcPlPrecisionEntries          GcPlPrecisionEntries
#define AcPl3dDwfOptions              GcPl3dDwfOptions
#define AcPlObject                    GcPlObject
#define AcPlDSDData                   GcPlDSDData
#define AcPlDSDEntry                  GcPlDSDEntry
#define AcPlObjectImp                 GcPlObjectImp       
#define AcPlPlotConfig                GcPlPlotConfig
#define AcPlPlotConfigInfo            GcPlPlotConfigInfo
#define AcPlPlotConfigManager         GcPlPlotConfigManager
#define AcPlPlotProgress              GcPlPlotProgress
#define AcPlPlotInfo                  GcPlPlotInfo
#define AcPlPlotEngine                GcPlPlotEngine
#define AcPlPlotPageInfo              GcPlPlotPageInfo
#define AcPlPlotErrorHandler          GcPlPlotErrorHandler
#define AcPlPlotFactory               GcPlPlotFactory
#define AcPlPlotInfoValidator         GcPlPlotInfoValidator
#define AcPlPlotLoggingErrorHandler   GcPlPlotLoggingErrorHandler
#define AcPlPlotProgressDialog        GcPlPlotProgressDialog
#define ACPLPLTPRGHELPPROC            GCPLPLTPRGHELPPROC
#define AcPlPlotReactor               GcPlPlotReactor
#define AcPlPlotReactorMgr            GcPlPlotReactorMgr
#define AcPlPrecisionEntry            GcPlPrecisionEntry
#define AcPlPlotLogger                GcPlPlotLogger
#define acplPlotConfigManagerPtr      gcplPlotConfigManagerPtr
#define acplPlotConfigManager         gcplPlotConfigManager
#define acplPlotReactorMgrPtr         gcplPlotReactorMgrPtr
#define acplCreatePlotProgressDialog  gcplCreatePlotProgressDialog
#define acplProcessPlotState          gcplProcessPlotState
#define acplPublishExecute            gcplPublishExecute
#define ACPL_DECLARE_MEMBERS          GCPL_DECLARE_MEMBERS
#define ACPL_DEFINE_MEMBERS           GCPL_DEFINE_MEMBERS

#define ACED_ARXCOMMAND_ENTRY_AUTO      GCED_GRXCOMMAND_ENTRY_AUTO
#define ACED_ARXCOMMAND_ENTRYBYID_AUTO  GCED_GRXCOMMAND_ENTRYBYID_AUTO
#define ACED_ADSSYMBOL_ENTRY_AUTO       GCED_GDSSYMBOL_ENTRY_AUTO
#define ACED_ADSCOMMAND_ENTRY_AUTO      GCED_GDSCOMMAND_ENTRY_AUTO
#define ACED_ADSSYMBOL_ENTRYBYID_AUTO   GCED_GDSSYMBOL_ENTRYBYID_AUTO
#define ACED_ADSCOMMAND_ENTRYBYID_AUTO  GCED_GDSCOMMAND_ENTRYBYID_AUTO
#define ACDB_REGISTER_OBJECT_ENTRY_AUTO GCDB_REGISTER_OBJECT_ENTRY_AUTO
//{{dynamic blocks
#define AcDbEvalGraph GcDbEvalGraph
#define AcDbEvalExpr GcDbEvalExpr
#define AcDbEvalConnectable GcDbEvalConnectable
#define AcDbEvalContext GcDbEvalContext
#define AcDbEvalContextIterator GcDbEvalContextIterator
#define AcDbDynBlockReferenceProperty GcDbDynBlockReferenceProperty
#define AcDbDynBlockReferencePropertyArray GcDbDynBlockReferencePropertyArray
#define AcDbDynBlockReferencePropertyArrayblkPropAry 	GcDbDynBlockReferencePropertyArrayblkPropAry
#define AcDbDynBlockReferencePropertyblkProp 		GcDbDynBlockReferencePropertyblkProp
#define AcDbEvalNodeId GcDbEvalNodeId
#define AcDbEvalNodeIdArray GcDbEvalNodeIdArray
#define AcDbEvalVariantArray GcDbEvalVariantArray
//}}
#define AcDbShHistory               GcDbShHistory
#define AcDbAssocPersSubentManager  GcDbAssocPersSubentManager 
#define AcDbShHistoryNode           GcDbShHistoryNode
#define AcDbShBoolean               GcDbShBoolean 
#define AcDbShPrimitive             GcDbShPrimitive
#define AcDbShBox                   GcDbShBox 
#define AcDbShBrep                  GcDbShBrep 
#define AcDbShChamfer               GcDbShChamfer 
#define AcDbShCylinder              GcDbShCylinder 
#define AcDbShExtrusion             GcDbShExtrusion 
#define AcDbShFillet                GcDbShFillet 
#define AcDbShLoft                  GcDbShLoft 
#define AcDbShPyramid               GcDbShPyramid 
#define AcDbShRevolve               GcDbShRevolve 
#define AcDbShSphere                GcDbShSphere 
#define AcDbShSubentColor           GcDbShSubentColor 
#define AcDbShSubentMaterial        GcDbShSubentMaterial 
#define AcDbShSweep                 GcDbShSweep 
#define AcDbShTorus                 GcDbShTorus 
#define AcDbShWedge                 GcDbShWedge 

#define AcDb3dProfile               GcDb3dProfile
#define AcDb3dProfileData           GcDb3dProfileData
#define AcDbLoftProfile             GcDbLoftProfile

#include "adsmigr.h"