#pragma once

//{{Redefine Class Section
#define	GcApLongTransactionManager 	OdApLongTransactionManager
#define	GcApLongTransactionReactor 	OdApLongTransactionReactor
#define	GcArray 	OdArray
#define	GcArrayMemCopyReallocator 	OdMemoryAllocator
#define	GcArrayObjectCopyReallocator 	OdObjectsAllocator
#define	GcCm 	OdCm
#define	GcCmColor 	OdCmColor
#define	GcCmEntityColor 	OdCmEntityColor
#define	GcCmTransparency 	OdCmTransparency
#define	GcDb2LineAngularDimension 	OdDb2LineAngularDimension
#define	GcDb2dPolyline 	OdDb2dPolyline
#define	GcDb2dVertex 	OdDb2dVertex
#define	GcDb3PointAngularDimension 	OdDb3PointAngularDimension
#define	GcDb3dPolyline 	OdDb3dPolyline
#define	GcDb3dPolylineVertex 	OdDb3dPolylineVertex
#define	GcDb3dSolid 	OdDb3dSolid
#define	GcDbAbstractViewTable 	OdDbAbstractViewTable
#define	GcDbAbstractViewTableIterator 	OdDbAbstractViewTableIterator
#define	GcDbAbstractViewTableRecord 	OdDbAbstractViewTableRecord
#define	GcDbAlignedDimension 	OdDbAlignedDimension
#define	GcDbArcDimension  OdDbArcDimension
#define	GcDbAppEntityGrips OdDbAppEntityGrips
#define	GcDbAppSystemVariables 	OdDbAppSystemVariables
#define	GcDbArc 	OdDbArc
#define	GcDbArcAlignedText 	OdDbArcAlignedText
#define	GcDbAttribute 	OdDbAttribute
#define	GcDbAttributeDefinition 	OdDbAttributeDefinition
#define	GcDbAuditInfo 	OdDbAuditInfo
#define	GcDbBlockBegin 	OdDbBlockBegin
#define	GcDbBlockChangeIterator 	OdDbBlockChangeIterator
#define	GcDbBlockEnd 	OdDbBlockEnd
#define	GcDbBlockInsertionPoints OdDbBlockInsertionPoints
#define	GcDbBlockReference 	OdDbBlockReference
#define	GcDbBlockReferenceIdIterator 	OdDbBlockReferenceIdIterator
#define	GcDbBlockTable 	OdDbBlockTable
#define	GcDbBlockTableIterator 	OdDbBlockTableIterator
#define	GcDbBlockTablePointer 	OdDbBlockTablePointer
#define	GcDbBlockTableRecord 	OdDbBlockTableRecord
#define	GcDbBlockTableRecordIterator 	OdDbBlockTableRecordIterator
#define	GcDbBlockTableRecordPointer 	OdDbBlockTableRecordPointer
#define	GcDbBody 	OdDbBody
#define	GcDbCircle 	OdDbCircle
#define	GcDbCompositeFilteredBlockIterator 	OdDbCompositeFilteredBlockIterator
#define	GcDbCurve 	OdDbCurve
#define	GcDbDatabase 	OdDbDatabase
#define	GcDbDatabaseIterator 	OdDbDatabaseIterator
#define	GcDbDatabaseReactor 	OdDbDatabaseReactor
#define	GcDbDatabaseSummaryInfo 	OdDbDatabaseSummaryInfo
#define	GcDbDate 	OdDbDate
#define	GcDbDeepCloneFiler 	OdDbDeepCloneFiler
#define	GcDbDiametricDimension 	OdDbDiametricDimension
#define	GcDbDictionary 	OdDbDictionary
#define	GcDbDictionaryIterator 	OdDbDictionaryIterator
#define	GcDbDictionaryPointer 	OdDbDictionaryPointer
#define	GcDbDictionaryWithDefault 	OdDbDictionaryWithDefault
#define	GcDbDimData 	OdDbDimData
#define	GcDbDimDataArray 	OdDbDimDataArray
#define	GcDbDimDataPtrArray 	OdDbDimDataPtrArray
#define	GcDbDimStyleTable 	OdDbDimStyleTable
#define	GcDbDimStyleTableIterator 	OdDbDimStyleTableIterator
#define	GcDbDimStyleTablePointer 	OdDbDimStyleTablePointer
#define	GcDbDimStyleTableRecord 	OdDbDimStyleTableRecord
#define	GcDbDimStyleTableRecordPointer 	OdDbDimStyleTableRecordPointer
#define	GcDbDimension 	OdDbDimension
#define	GcDbDoubleClickEdit 	GcDbDoubleClickEdit
#define	GcDbDwgFiler 	OdDbDwgFiler
#define	GcDbDxfFiler 	OdDbDxfFiler
#define	GcDbDynBlockReference 	OdDbDynBlockReference
#define GcDbDynBlockTableRecord   OdDbDynBlockTableRecord
#define	GcDbEllipse 	OdDbEllipse
#define	GcDbGripPointsPE  OdDbGripPointsPE
#define	GcDbEntityIntersectionPE  OdDbEntityIntersectionPE
#define GcDbPaperOrientationPE OdDbPaperOrientationPE
#define	GcDbEntity 	OdDbEntity
#define	GcDbEntityHyperlinkPE 	OdDbEntityHyperlinkPE
#define	GcDbEntityPointer 	OdDbEntityPointer
#define	GcDbEntityReactor 	OdDbEntityReactor
#define	GcDbExtents 	OdDbExtents
#define	GcDbFace 	OdDbFace
#define	GcDbFaceRecord 	OdDbFaceRecord
#define	GcDbFcf 	OdDbFcf
#define	GcDbField 	OdDbField
#define GcDbFieldArray OdDbFieldArray
#define GcFieldValue OdFieldValue
#define	GcDbFilter 	OdDbFilter
#define	GcDbFilteredBlockIterator 	OdDbFilteredBlockIterator
#define	GcDbFrame 	OdDbFrame
#define	GcDbFullSubentPath 	OdDbFullSubentPath
#define	GcDbFullSubentPathArray 	OdDbFullSubentPathArray
#define	GcDbGraph 	OdDbGraph
#define	GcDbGraphNode 	OdDbGraphNode
#define	GcDbGraphStack 	OdDbGraphStack
#define	GcDbGripData 	OdDbGripData
#define	GcDbGripDataArray 	OdDbGripDataArray
#define	GcDbGripDataPtrArray 	OdDbGripDataPtrArray
#define	GcDbGroup 	OdDbGroup
#define	GcDbGroupIterator 	OdDbGroupIterator
#define	GcDbHandle 	OdDbHandle
#define	GcDbHardOwnershipId 	OdDbHardOwnershipId
#define	GcDbHardPointerId 	OdDbHardPointerId
#define	GcDbHatch 	OdDbHatch
#define	GcDbHelix OdDbHelix
#define	GcDbHostApplicationProgressMeter 	OdDbHostApplicationProgressMeter
#define	GcDbHostApplicationServiceRestrictions 	OdDbHostApplicationServiceRestrictions
#define	GcDbHostApplicationServices 	OdDbHostAppServices
#define	GcDbHyperlink 	OdDbHyperlink
#define	GcDbHyperlinkCollection 	OdDbHyperlinkCollection
#define	GcDbIdMapping 	OdDbIdMapping
#define	GcDbIdMappingIter 	OdDbIdMappingIter
#define	GcDbIdPair 	OdDbIdPair
#define	GcDbImage 	OdDbImage
#define	GcDbIndex 	OdDbIndex
#define	GcDbIndexUpdateData 	OdDbIndexUpdateData
#define	GcDbIndexUpdateDataIterator 	OdDbIndexUpdateDataIterator
#define	GcDbIntArray 	OdDbIntArray
#define	GcDbArrayIntArray OdDbArrayIntArray
#define	GcDbLayerFilter 	OdDbLayerFilter
#define	GcDbLayerIndex 	OdDbLayerIndex
#define	GcDbLayerIndexIterator 	OdDbLayerIndexIterator
#define	GcDbLayerTable 	OdDbLayerTable
#define	GcDbLayerTableIterator 	OdDbLayerTableIterator
#define	GcDbLayerTablePointer 	OdDbLayerTablePointer
#define	GcDbLayerTableRecord 	OdDbLayerTableRecord
#define	GcDbLayerTableRecordPointer 	OdDbLayerTableRecordPointer
#define	GcDbLayout 	OdDbLayout
#define	GcDbLayoutManager 	OdDbLayoutManager
#define	GcDbLayoutManagerReactor 	OdDbLayoutManagerReactor
#define	GcDbLeader 	OdDbLeader
#define	GcDbLight 	OdDbLight
#define	GcDbLine 	OdDbLine
#define	GcDbLoftedSurface OdDbLoftedSurface
#define	GcDbMLeader OdDbMLeader
#define GcDbMLeaderStyle OdDbMLeaderStyle
#define	GcDbLinetypeTable 	OdDbLinetypeTable
#define	GcDbLinetypeTableIterator 	OdDbLinetypeTableIterator
#define	GcDbLinetypeTablePointer 	OdDbLinetypeTablePointer
#define	GcDbLinetypeTableRecord 	OdDbLinetypeTableRecord
#define	GcDbLinetypeTableRecordPointer 	OdDbLinetypeTableRecordPointer
#define	GcDbLoftOptions  	OdDbLoftOptions 
#define	GcDbLongTransWorkSetIterator 	OdDbLongTransWorkSetIterator
#define	GcDbLongTransaction 	OdDbLongTransaction
#define	GcDbMInsertBlock 	OdDbMInsertBlock
#define	GcDbMPolygon 	OdDbMPolygon
#define	GcDbMText 	OdDbMText
#define	GcDbMTextFragment 	OdDbMTextFragment
#define	GcDbMatchProperties 	OdDbMatchProperties
#define	GcDbMaterial 	OdDbMaterial
#define	GcDbMentalRayRenderSettings 	OdDbMentalRayRenderSettings
#define	GcDbMline 	OdDbMline
#define	GcDbMlineStyle 	OdDbMlineStyle
#define	GcDbObject 	OdDbObject
#define	GcDbObjectContextInterface 	OdDbObjectContextInterface
#define	GcDbObjectId 	OdDbObjectId
#define	GcDbObjectIdArray 	OdDbObjectIdArray
#define	GcDbObjectIdGraph 	OdDbObjectIdGraph
#define	GcDbObjectIdGraphNode 	OdDbObjectIdGraphNode
#define	GcDbObjectIterator 	OdDbObjectIterator
#define	GcDbObjectPointer 	OdDbObjectPointer
#define	GcDbObjectPointerBase 	OdDbObjectPointerBase
#define	GcDbObjectReactor 	OdDbObjectReactor
#define	GcDbOle2Frame 	OdDbOle2Frame
#define	GcDbOleFrame 	OdDbOleFrame
#define	GcDbOrdinateDimension 	OdDbOrdinateDimension
#define	GcDbPersistentObjectReactor 	OdDbPersistentObjectReactor
#define	GcDbPlaceHolder 	OdDbPlaceHolder
#define	GcDbPlotSettings 	OdDbPlotSettings
#define	GcDbPlotSettingsValidator 	OdDbPlotSettingsValidator
#define	GcDbPoint 	OdDbPoint
#define	GcDbPolyFaceMesh 	OdDbPolyFaceMesh
#define	GcDbPolyFaceMeshVertex 	OdDbPolyFaceMeshVertex
#define	GcDbPolygonMesh 	OdDbPolygonMesh
#define	GcDbPolygonMeshVertex 	OdDbPolygonMeshVertex
#define	GcDbPolyline 	OdDbPolyline
#define	GcDbProxyEntity 	OdDbProxyEntity
#define	GcDbProxyObject 	OdDbProxyObject
#define	GcDbR13ObjectId 	OdDbR13ObjectId
#define	GcDbRadialDimension 	OdDbRadialDimension
#define	GcDbRadialDimensionLarge  OdDbRadialDimensionLarge
#define	GcDbRasterImage 	OdDbRasterImage
#define	GcDbRasterImageDef 	OdDbRasterImageDef
#define	GcDbRasterImageDefFileAccessReactor 	OdDbRasterImageDefFileAccessReactor
#define	GcDbRasterImageDefReactor 	OdDbRasterImageDefReactor
#define	GcDbRasterImageDefTransReactor 	OdDbRasterImageDefTransReactor
#define	GcDbRasterVariables 	OdDbRasterVariables
#define	GcDbRay 	OdDbRay
#define	GcDbRecover 	OdDbRecover
#define	GcDbRecoverCallBack 	OdDbRecoverCallBack
#define	GcDbRegAppTable 	OdDbRegAppTable
#define	GcDbRegAppTableIterator 	OdDbRegAppTableIterator
#define	GcDbRegAppTablePointer 	OdDbRegAppTablePointer
#define	GcDbRegAppTableRecord 	OdDbRegAppTableRecord
#define	GcDbRegAppTableRecordPointer 	OdDbRegAppTableRecordPointer
#define	GcDbRegion 	OdDbRegion
#define	GcDbRenderEnvironment 	OdDbRenderEnvironment
#define	GcDbRenderGlobal 	OdDbRenderGlobal
#define	GcDbRenderSettings 	OdDbRenderSettings
#define	GcDbRotatedDimension 	OdDbRotatedDimension
#define	GcDbSection 	OdDbSection
#define	GcDbSectionManager 	OdDbSectionManager
#define	GcDbSectionManagerIterator 	OdDbSectionManagerIterator
#define	GcDbSectionSettings 	OdDbSectionSettings
#define	GcDbSequenceEnd 	OdDbSequenceEnd
#define	GcDbServices 	OdDbServices
#define	GcDbShape 	OdDbShape
#define	GcDbSoftOwnershipId 	OdDbSoftOwnershipId
#define	GcDbSoftPointerId 	OdDbSoftPointerId
#define	GcDbSolid 	OdDbSolid
#define	GcDbSortentsTable 	OdDbSortentsTable
#define	GcDbSpatialFilter 	OdDbSpatialFilter
#define	GcDbSpatialIndex 	OdDbSpatialIndex
#define	GcDbSpatialIndexIterator 	OdDbSpatialIndexIterator
#define	GcDbSpline 	OdDbSpline
#define	GcDbSurface OdDbSurface
#define	GcDbStub     	OdDbStub    
#define	GcDbSubentId 	OdDbSubentId
#define	GcDbSummaryInfoManager 	OdDbSummaryInfoManager
#define	GcDbSummaryInfoReactor 	OdDbSummaryInfoReactor
#define	GcDbSymbolTable 	OdDbSymbolTable
#define	GcDbSymbolTableIterator 	OdDbSymbolTableIterator
#define	GcDbSymbolTablePointer 	OdDbSymbolTablePointer
#define	GcDbSymbolTableRecord 	OdDbSymbolTableRecord
#define	GcDbSymbolTableRecordPointer 	OdDbSymbolTableRecordPointer
#define	GcDbTable 	OdDbTable
#define	GcDbTableStyle 	OdDbTableStyle
#define GcCellRange OdCellRange
#define	GcDbText 	OdDbText
#define	GcDbTextStyleTable 	OdDbTextStyleTable
#define	GcDbTextStyleTableIterator 	OdDbTextStyleTableIterator
#define	GcDbTextStyleTablePointer 	OdDbTextStyleTablePointer
#define	GcDbTextStyleTableRecord 	OdDbTextStyleTableRecord
#define	GcDbTextStyleTableRecordPointer 	OdDbTextStyleTableRecordPointer
#define	GcDbTrace 	OdDbTrace
#define	GcDbUnderlayReference OdDbUnderlayReference
#define	GcDbTransactionManager 	OdDbTransactionManager
#define gcdbTransactionManagerPtr oddbTransactionManagerPtr
#define gcdbTransactionManager oddbTransactionManager
#define	GcDbUCSTable 	OdDbUCSTable
#define	GcDbUCSTableIterator 	OdDbUCSTableIterator
#define	GcDbUCSTablePointer 	OdDbUCSTablePointer
#define	GcDbUCSTableRecord 	OdDbUCSTableRecord
#define	GcDbUCSTableRecordPointer 	OdDbUCSTableRecordPointer
#define	GcDbVertex 	OdDbVertex
#define	GcDbViewTable 	OdDbViewTable
#define	GcDbViewTableIterator 	OdDbViewTableIterator
#define	GcDbViewTablePointer 	OdDbViewTablePointer
#define	GcDbViewTableRecord 	OdDbViewTableRecord
#define	GcDbViewTableRecordPointer 	OdDbViewTableRecordPointer
#define	GcDbViewport 	OdDbViewport
#define	GcDbViewportTable 	OdDbViewportTable
#define	GcDbViewportTableIterator 	OdDbViewportTableIterator
#define	GcDbViewportTablePointer 	OdDbViewportTablePointer
#define	GcDbViewportTableRecord 	OdDbViewportTableRecord
#define	GcDbViewportTableRecordPointer 	OdDbViewportTableRecordPointer
#define	GcDbVisualStyle 	OdDbVisualStyle
#define	GcDbVoidPtrArray 	OdDbVoidPtrArray
#define	GcDbWblockCloneFiler 	OdDbWblockCloneFiler
#define	GcDbWipeout 	OdDbWipeout
#define	GcDbWipeoutVariables 	OdDbWipeoutVariables
#define GcDbAnnotativeObjectPE OdDbAnnotativeObjectPE
#define	GcDbXObject 	OdDbXObject
#define	GcDbXline 	OdDbXline
#define	GcDbXrecord 	OdDbXrecord
#define	GcDbXrecordIterator 	OdDbXrecordIterator
#define	GcDbXrefGraph 	OdDbXrefGraph
#define	GcDbXrefGraphNode 	OdDbXrefGraphNode
#define	GcDbXrefObjectId 	OdDbXrefObjectId
#define GcDbDimAssoc      OdDbDimAssoc
#define GcDbLayerStateManager OdDbLayerStateManager
#define GcDbColor OdDbColor
#define GcDbSubDMesh OdDbSubDMesh
#define GcDbPdfReference OdDbPdfReference
#define GcDbDwfReference OdDbDwfReference
#define GcDbDgnReference OdDbDgnReference
#define GcDbUnderlayDefinition OdDbUnderlayDefinition
#define GcDbDgnDefinition OdDbDgnDefinition
#define GcDbBreakData OdDbBreakData
#define GcDbBreakPointRef OdDbBreakPointRef
#define GcDbRevolveOptions OdDbRevolveOptions
#define GcDbRevolvedSurface OdDbRevolvedSurface
#define GcDbUnderlayHost OdDbUnderlayHost
#define GcDbUnderlayItem OdDbUnderlayItem
#define GcDbUnderlayFile OdDbUnderlayFile
#define GcDbSweepOptions OdDbSweepOptions
#define GcDbPlaneSurface OdDbPlaneSurface
#define GcDbExtrudedSurface OdDbExtrudedSurface
#define GcDbSweptSurface OdDbSweptSurface
#define GcDbNurbSurface OdDbNurbSurface
#define GcDbNurbSurfaceArray OdDbNurbSurfaceArray
#define GcDbPointRef OdDbPointRef
#define GcDbOsnapPointRef OdDbOsnapPointRef
#define GcDbLinkedTableData OdDbLinkedTableData
#define GcDbCamera OdDbCamera
#define GcDmUtil   OdDmUtil
#define	GcEdCommand 	OdEdCommand
#define	GcEdCommandIterator 	OdEdCommandIterator
#define	GcEdCommandStack 	OdEdCommandStack
#define	GcEdCommandStruc 	OdEdCommandStruc
#define	GcEdServices 	OdEdServices
#define	GcEdSymUtilServices 	OdEdSymUtilServices
#define	GcEdUIContext 	OdEdUIContext
#define	GcEdXrefFileLock 	OdEdXrefFileLock
#define	GcEditor 	OdEditor
#define	GcEditorReactor 	OdEditorReactor
#define GcFdFieldReactor  OdFdFieldReactor
#define GcFdFieldEngine   OdFdFieldEngine
#define	GcGe 	OdGe
#define	GcGeAugPolyline3d 	OdGeAugPolyline3d
#define	GcGeBoundBlock2d 	OdGeBoundBlock2d
#define	GcGeBoundBlock3d 	OdGeBoundBlock3d
#define	GcGeBoundedPlane 	OdGeBoundedPlane
#define	GcGeCircArc2d 	OdGeCircArc2d
#define	GcGeCircArc3d 	OdGeCircArc3d
#define	GcGeClipBoundary2d 	OdGeClipBoundary2d
#define	GcGeCompositeCurve2d 	OdGeCompositeCurve2d
#define	GcGeCompositeCurve3d 	OdGeCompositeCurve3d
#define	GcGeCone 	OdGeCone
#define	GcGeContext 	OdGeContext
#define	GcGeCubicSplineCurve2d 	OdGeCubicSplineCurve2d
#define	GcGeCubicSplineCurve3d 	OdGeCubicSplineCurve3d
#define	GcGeCurve2d 	OdGeCurve2d
#define	GcGeCurve3d 	OdGeCurve3d
#define	GcGeCurveBoundary 	OdGeCurveBoundary
#define	GcGeCurveCurveInt2d 	OdGeCurveCurveInt2d
#define	GcGeCurveCurveInt3d 	OdGeCurveCurveInt3d
#define	GcGeCurveSurfInt 	OdGeCurveSurfInt
#define	GcGeCylinder 	OdGeCylinder
#define	GcGeDoubleArray 	OdGeDoubleArray
#define	GcGeDwgIO 	OdGeDwgIO
#define	GcGeDxfIO 	OdGeDxfIO
#define	GcGeEllipArc2d 	OdGeEllipArc2d
#define	GcGeEllipArc3d 	OdGeEllipArc3d
#define	GcGeEntity2d 	OdGeEntity2d
#define	GcGeEntity3d 	OdGeEntity3d
#define	GcGeError 	OdGeError
#define	GcGeExternalBoundedSurface 	OdGeExternalBoundedSurface
#define	GcGeExternalCurve2d 	OdGeExternalCurve2d
#define	GcGeExternalCurve3d 	OdGeExternalCurve3d
#define	GcGeExternalSurface 	OdGeExternalSurface
#define	GcGeFileIO 	OdGeFileIO
#define	GcGeFiler 	OdGeFiler
#define	GcGeIntArray 	OdGeIntArray
#define	GcGeIntersectError 	OdGeIntersectError
#define	GcGeInterval 	OdGeInterval
#define	GcGeKnotVector 	OdGeKnotVector
#define	GcGeLibVersion 	OdGeLibVersion
#define	GcGeLine2d 	OdGeLine2d
#define	GcGeLine3d 	OdGeLine3d
#define	GcGeLineSeg2d 	OdGeLineSeg2d
#define	GcGeLineSeg3d 	OdGeLineSeg3d
#define	GcGeLinearEnt2d 	OdGeLinearEnt2d
#define	GcGeLinearEnt3d 	OdGeLinearEnt3d
#define	GcGeMatrix2d 	OdGeMatrix2d
#define	GcGeMatrix3d 	OdGeMatrix3d
#define	GcGeNurbCurve2d 	OdGeNurbCurve2d
#define	GcGeNurbCurve3d 	OdGeNurbCurve3d
#define	GcGeNurbSurface 	OdGeNurbSurface
#define	GcGeOffsetCurve2d 	OdGeOffsetCurve2d
#define	GcGeOffsetCurve3d 	OdGeOffsetCurve3d
#define	GcGeOffsetSurface 	OdGeOffsetSurface
#define	GcGePlanarEnt 	OdGePlanarEnt
#define	GcGePlane 	OdGePlane
#define	GcGePoint2d 	OdGePoint2d
#define	GcGePoint2dArray 	OdGePoint2dArray
#define	GcGePoint3d 	OdGePoint3d
#define	GcGePoint3dArray 	OdGePoint3dArray
#define	GcGePointEnt2d 	OdGePointEnt2d
#define	GcGePointEnt3d 	OdGePointEnt3d
#define	GcGePointOnCurve2d 	OdGePointOnCurve2d
#define	GcGePointOnCurve3d 	OdGePointOnCurve3d
#define	GcGePointOnSurface 	OdGePointOnSurface
#define	GcGePolyline2d 	OdGePolyline2d
#define	GcGePolyline3d 	OdGePolyline3d
#define	GcGePosition2d 	OdGePosition2d
#define	GcGePosition3d 	OdGePosition3d
#define	GcGeRay2d 	OdGeRay2d
#define	GcGeRay3d 	OdGeRay3d
#define	GcGeScale2d 	OdGeScale2d
#define	GcGeScale3d 	OdGeScale3d
#define	GcGeSphere 	OdGeSphere
#define	GcGeSplineEnt2d 	OdGeSplineEnt2d
#define	GcGeSplineEnt3d 	OdGeSplineEnt3d
#define	GcGeSurfSurfInt 	OdGeSurfSurfInt
#define	GcGeSurface 	OdGeSurface
#define	GcGeTol 	OdGeTol
#define	GcGeTorus 	OdGeTorus
#define	GcGeVector2d 	OdGeVector2d
#define	GcGeVector2dArray 	OdGeVector2dArray
#define	GcGeVector3d 	OdGeVector3d
#define	GcGeVector3dArray 	OdGeVector3dArray
#define	GcGeVoidPointerArray 	OdGeVoidPointerArray
#define	GcGeXConfig 	OdGeXConfig
#define	GcGiCommonDraw 	OdGiCommonDraw
#define	GcGiContext 	OdGiContext
#define	GcGiDrawable 	OdGiDrawable
#define	GcGiDrawableTraits 	OdGiDrawableTraits
#define	GcGiEdgeData 	OdGiEdgeData
#define	GcGiEdgeStyle 	OdGiEdgeStyle
#define	GcGiFaceData 	OdGiFaceData
#define	GcGiFaceStyle 	OdGiFaceStyle
#define	GcGiGeometry 	OdGiGeometry
#define	GcGiLightAttenuation 	OdGiLightAttenuation
#define	GcGiMapper  	OdGiMapper
#define	GcGiMaterialColor 	OdGiMaterialColor
#define	GcGiMaterialMap  	OdGiMaterialMap
#define	GcGiMaterialTraits 	OdGiMaterialTraits
#define	GcGiMrDiagnosticGridMode 	OdGiMrDiagnosticGridMode
#define	GcGiMrFilter 	OdGiMrFilter
#define	GcGiShadowParameters 	OdGiShadowParameters
#define GcGiShadowParameters2 OdGiShadowParameters2
#define	GcGiSubEntityTraits 	OdGiSubEntityTraits
#define	GcGiTextEngine 	OdGiTextEngine
#define	GcGiTextStyle 	OdGiTextStyle
#define	GcGiVertexData 	OdGiVertexData
#define	GcGiViewport 	OdGiViewport
#define	GcGiViewportDraw 	OdGiViewportDraw
#define	GcGiViewportGeometry 	OdGiViewportGeometry
#define	GcGiVisibility 	OdGiVisibility
#define	GcGiVisualStyle OdGiVisualStyle
#define GcGiVisualStyleProperties OdGiVisualStyleProperties
#define	GcGiWorldDraw 	OdGiWorldDraw
#define	GcGiWorldGeometry 	OdGiWorldGeometry
#define GcGiPolyline	OdGiPolyline
#define GcGiLineType	OdGiLinetype
#define GcGiColorRGB	OdGiColorRGB
#define GcGiColorRGBA   OdGiColorRGBA
#define GcGiPixelBGRA32 OdGiPixelBGRA32
#define GcGiImageBGRA32 OdGiImageBGRA32
#define GcGiVariant OdGiVariant
#define GcGiVisualStyleProperties OdGiVisualStyleProperties
#define GcGiVisualStyleOperations OdGiVisualStyleOperations
#define GcGiVisualStyleTraits OdGiVisualStyleTraits
//#define	GcGs2DViewLimitManager 	OdGs2DViewLimitManager  // GCAD
//#define	GcGsClassFactory 	OdGsClassFactory  // GCAD
#define	GcGsMarker  OdGsMarker
#define	GcGsColor 	OdGsColor
//#define	GcGsConfig 	OdGsConfig  // GCAD
#define	GcGsDCPoint 	OdGsDCPoint
#define	GcGsDCRect 	OdGsDCRect
#define	GcGsDevice 	OdGsDevice
//#define	GcGsManager 	OdGsManager // GCAD
#define	GcGsModel 	OdGsModel
#define	GcGsNode 	OdGsNode
#define	GcGsPath 	OdGsPath
#define	GcGsReactor 	OdGsReactor
//#define	GcGsScreenShot 	OdGsScreenShot  // GCAD
#define	GcGsView 	OdGsView
#define	GcLyAndExpr  	OdLyAndExpr
#define	GcLyBoolExpr  	OdLyBoolExpr
#define	GcLyLayerFilter  	OdLyLayerFilter
#define	GcLyLayerFilterManager  	OdLyLayerFilterManager
#define	GcLyLayerGroup  	OdLyLayerGroup
#define	GcLyRelExpr  	OdLyRelExpr
#define	GcRxClass 	OdRxClass
#define	GcRxDLinkerReactor 	OdRxDLinkerReactor
#define	GcRxDictionary 	OdRxDictionary
#define	GcRxDictionaryIterator 	OdRxDictionaryIterator
#define	GcRxDynamicLinker 	OdRxDynamicLinker
#define	GcRxEvent 	OdRxEvent
#define	GcRxEventReactor 	OdRxEventReactor
#define	GcRxIterator 	OdRxIterator
#define	GcRxKernel 	OdRxKernel
#define	GcRxObject 	OdRxObject
#define	GcRxProtocolReactor OdRxProtocolReactor
#define	GcRxProtocolReactorIterator OdRxProtocolReactorIterator
#define	GcRxProtocolReactorList OdRxProtocolReactorList
#define	GcRxProtocolReactorListIterator OdRxProtocolReactorListIterator
#define	GcRxProtocolReactorManager OdRxProtocolReactorManager
#define	GcRxProtocolReactorManagerFactory OdRxProtocolReactorManagerFactory
#define	GcRxService 	OdRxService
#define	GcString 	OdString
#define GcStringArray OdStringArray
#define	GcTransaction 	OdTransaction
#define	GcTransactionManager 	OdTransactionManager
#define	GcTransactionReactor 	OdTransactionReactor
#define GcUnderlayLayer OdUnderlayLayer
#define GcDbLayerStateManagerReactor OdDbLayerStateManagerReactor
//#define	GcadAppInfo 	GcadAppInfo  // GCAD
//#define	CGcExtensionModule 	CGcExtensionModule
//#define	CGcModuleResourceOverride 	CGcModuleResourceOverride
//}}

//{{Redefine Enum Section
#define GcXrefSubCommand OdXrefSubCommand
#define	GcDbDwgVersion 	DwgVersion
#define	GcDbGripOperations 	OdDbGripOperations
#define	GcGiArcType 	OdGiArcType
#define	GcGiColorIntensity 	OdGiColorIntensity
#define	GcGiDeviationType 	OdGiDeviationType
#define	GcGiFillType 	OdGiFillType
#define	GcGiImageOrg 	OdGiImageOrg
#define	GcGiImageOrient 	OdGiImageOrient
#define	GcGiOrientationType 	OdGiOrientationType
#define	GcGiRegenType 	OdGiRegenType
#define	eGcGiRegenTypeInvalid 	eOdGiRegenTypeInvalid
#define	kGcGiArcChord 	kOdGiArcChord
#define	kGcGiArcSector 	kOdGiArcSector
#define	kGcGiArcSimple 	kOdGiArcSimple
#define	kGcGiFillAlways 	kOdGiFillAlways
#define	kGcGiFillNever 	kOdGiFillNever
#define	kGcGiForExplode 	kOdGiForExplode
#define	kGcGiForExtents 	kOdGiForExtents
#define	kGcGiHideOrShadeCommand 	kOdGiHideOrShadeCommand
#define kGcGiShadedDisplay kOdGiShadedDisplay
#define	kGcGiInvisible 	kOdGiInvisible
#define	kGcGiMaxDevForBoundary 	kOdGiMaxDevForBoundary
#define	kGcGiMaxDevForCircle 	kOdGiMaxDevForCircle
#define	kGcGiMaxDevForCurve 	kOdGiMaxDevForCurve
#define	kGcGiMaxDevForFacet 	kOdGiMaxDevForFacet
#define	kGcGiMaxDevForIsoline 	kOdGiMaxDevForIsoline
#define	kGcGiRenderCommand 	kOdGiRenderCommand
#define	kGcGiSaveWorldDrawForProxy 	kOdGiSaveWorldDrawForProxy
//#define	kGcGiSaveWorldDrawForR12 	/* discarded */
#define	kGcGiSilhouette 	kOdGiSilhouette
#define	kGcGiStandardDisplay 	kOdGiStandardDisplay
#define	kGcGiVisible 	kOdGiVisible

#define	kOnGCADStartup 	kOnDWGdirectStartup
#define	kProd_GcDb 	kProd_OdDb

#define kGcGiWorldPosition 	kOdGiWorldPosition
#define kGcGiViewportPosition 	kOdGiViewportPosition,
#define kGcGiScreenPosition 	kOdGiScreenPosition
#define kGcGiScreenLocalOriginPosition kOdGiScreenLocalOriginPosition
#define kGcGiWorldWithScreenOffsetPosition kOdGiWorldWithScreenOffsetPosition
#define GcGiPositionTransformBehavior OdGiPositionTransformBehavior

#define kGcGiWorldScale 	kOdGiWorldScale    
#define kGcGiViewportScale 	kOdGiViewportScale
#define kGcGiScreenScale 	kOdGiScreenScale
#define kGcGiViewportLocalOriginScale kOdGiViewportLocalOriginScale
#define kGcGiScreenLocalOriginScale kOdGiScreenLocalOriginScale
#define GcGiScaleTransformBehavior OdGiScaleTransformBehavior

#define kGcGiWorldOrientation  kOdGiWorldOrientation
#define kGcGiScreenOrientation kOdGiScreenOrientation
#define kGcGiZAxisOrientation  kOdGiZAxisOrientation
#define GcGiOrientationTransformBehavior OdGiOrientationTransformBehavior

#define MaintenanceReleaseVersion MaintReleaseVer
//}}

//{{Redefine Func Section
#define	gcTransactionManagerPtr 	odTransactionManagerPtr
#define	gcapLongTransactionManagerPtr 	odapLongTransactionManagerPtr
#define	gcdbAlloc 	    gcad_malloc
#define	gcdbFree 	      gcad_free
#define	gcdbGetGdsName 	oddbGetAdsName
#define	gcdbGetExtnames 	oddbGetExtnames
#define	gcdbGetObjectId 	oddbGetObjectId
#define	gcdbHostApplicationServices 	oddbHostApplicationServices
#define	gcdbOpenGcDbEntity 	oddbOpenOdDbEntity
#define	gcdbOpenGcDbObject 	oddbOpenOdDbObject
#define	gcdbOpenObject 	oddbOpenObject
#define	gcdbRealloc 	gcad_realloc
#define	gcdbSetExtnames 	oddbSetExtnames
#define gcdbGroupCodeToType	oddbGroupCodeToType
#define gcdbGetFieldEngine oddbGetFieldEngine
#define gddbGetGeoDataObjId oddbGetGeoDataObjId
#define	gclyGetLayerFilterManager  	odlyGetLayerFilterManager
#define	gcrxAppIsLoaded 	odrxAppIsLoaded
#define	gcrxApplicationIsLocked 	odrxApplicationIsLocked
#define	gcrxBuildClassHierarchy 	odrxBuildClassHierarchy
#define	gcrxGetServiceSymbolAddr 	odrxGetServiceSymbolAddr
#define	gcrxIsAppMDIAware 	odrxIsAppMDIAware
#define	gcrxLoadApp 	odrxLoadApp
#define	gcrxLoadModule 	odrxLoadModule
#define	gcrxLoadedApps 	odrxLoadedApps
#define	gcrxLockApplication 	odrxLockApplication
#define	gcrxRegisterApp 	odrxRegisterApp
#define	gcrxRegisterAppMDIAware 	odrxRegisterAppMDIAware
#define	gcrxRegisterAppNotMDIAware 	odrxRegisterAppNotMDIAware
#define	gcrxRegisterService 	odrxRegisterService
#define	gcrxServiceIsRegistered 	odrxServiceIsRegistered
#define	gcrxSysRegistry 	odrxSysRegistry
#define	gcrxUnloadApp 	odrxUnloadApp
#define	gcrxUnloadModule 	odrxUnloadModule
#define	gcrxUnlockApplication 	odrxUnlockApplication
#define	gcrxUnregisterApp 	odrxUnregisterApp
#define gcdbGroupCodeToType oddbGroupCodeToType
#define	deleteGcRxClass 	deleteOdRxClass
#define GcPositive        OdPositive
#define GcNegative        OdNegative
#define GcZero            OdZero
#define GcNonZero         OdNonZero
#define GcEqual           OdEqual
#define GcLess            OdLess
#define GcLessOrEqual     OdLessOrEqual
#define GcGreater         OdGreater
#define GcGreaterOrEqual  OdGreaterOrEqual
#define GcCmpDouble       OdCmpDouble
#define gcSScanf          odSScanf
#define gcdbGetSummaryInfo oddbGetSummaryInfo
#define gcdbPutSummaryInfo oddbPutSummaryInfo
#define gcdbValidateCustomSummaryInfoKey oddbValidateCustomSummaryInfoKey
#define gcdbSummaryInfoManager oddbSummaryInfoManager
//}}

//{{Redefine Macro Section
#define	GCDB_DECLARE_MEMBERS 	ODDB_DECLARE_MEMBERS
#define	GCRX_CLASS_DICTIONARY 	ODRX_CLASS_DICTIONARY
#define GCRX_DEFINE_MEMBERS     ODRX_DEFINE_MEMBERS
#define	GCRX_CMD_DEFUN 	OdEdCommand::kDefun
#define	GCRX_CMD_DOCEXCLUSIVELOCK 	OdEdCommand::kDocExclusiveLock
#define	GCRX_CMD_DOCREADLOCK 	OdEdCommand::kDocReadLock
#define	GCRX_CMD_INPROGRESS 	OdEdCommand::kInProgress
#define	GCRX_CMD_INTERRUPTIBLE 	OdEdCommand::kInterruptible
#define	GCRX_CMD_MODAL 	OdEdCommand::kModal
#define	GCRX_CMD_NOBEDIT 	OdEdCommand::kNoBedit
#define	GCRX_CMD_NOHISTORY 	OdEdCommand::kNoHistory
#define	GCRX_CMD_NOINTERNALLOCK 	OdEdCommand::kNoInternalLock
#define	GCRX_CMD_NOMULTIPLE 	OdEdCommand::kNoMultiple
#define	GCRX_CMD_NONEWSTACK 	OdEdCommand::kNoNewStack
#define	GCRX_CMD_NOOEM 	OdEdCommand::kNoOEM
#define	GCRX_CMD_NOPAPERSPACE 	OdEdCommand::kNoPaperspace
#define	GCRX_CMD_NOPERSPECTIVE 	OdEdCommand::kNoPerspective
#define	GCRX_CMD_NOTILEMODE 	OdEdCommand::kNoTilemode
#define	GCRX_CMD_NO_UNDO_MARKER 	OdEdCommand::kNoUndoMarker
#define	GCRX_CMD_PLOTONLY 	OdEdCommand::kPlotOnly
#define	GCRX_CMD_REDRAW 	OdEdCommand::kRedraw
#define	GCRX_CMD_SESSION 	OdEdCommand::kSession
#define	GCRX_CMD_TRANSPARENT 	OdEdCommand::kTransparent
#define	GCRX_CMD_UNDEFINED 	OdEdCommand::kUndefined
#define	GCRX_CMD_USEPICKSET 	OdEdCommand::kUsePickset
#define GCRX_CMD_LISPASCMD OdEdCommand::kLispAsCmd
#define	GCRX_CONS_DEFINE_MEMBERS 	ODRX_CONS_DEFINE_MEMBERS2
#define	GCRX_DECLARE_MEMBERS 	ODRX_DECLARE_MEMBERS
#define	GCRX_DXF_DEFINE_MEMBERS 	ODRX_DXF_CONS_DEFINE_MEMBERS
#define	GCRX_EVENT_OBJ 	ODRX_EVENT_OBJ
#define	GCRX_NO_CONS_DEFINE_MEMBERS 	ODRX_NO_CONS_DEFINE_MEMBERS
#define	GCRX_NO_CONS_DEFINE_MEMBERS_TEMPLARG 	ODRX_NO_CONS_DEFINE_MEMBERS_TEMPLARG
#define	GCRX_PROTOCOL_REACTOR_MANAGER_AT ODRX_PROTOCOL_REACTOR_MANAGER_AT
#define	GCRX_PROTOCOL_REACTOR_LIST_AT ODRX_PROTOCOL_REACTOR_LIST_AT
#define GCDB_INFINITE_XCLIP_DEPTH ODDB_INFINITE_XCLIP_DEPTH
#define GCDB_ANNOTATIONSCALES_COLLECTION ODDB_ANNOTATIONSCALES_COLLECTION
#define	gcapLongTransactionManager 	odapLongTransactionManager
#define	gcedEditor 	odedEditor()
#define	GcEditorReactor 	OdEditorReactor
#define	GcEditorReactor2 	OdEditorReactor2
#define	gcedRegCmds 	odedRegCmds().get()
#define	gcrxClassDictionary 	odrxClassDictionary().get()
#define	gcrxDynamicLinker 	odrxDynamicLinker()
#define	gcrxEvent 	odrxEvent()
#define	gcrxProtocolReactors odrxProtocolReactors
#define	gcrxServiceDictionary 	odrxServiceDictionary().get()
#define	gctrTransactionManager 	odtrTransactionManager
#define gcdbResurrectMeNow oddbResurrectMeNow
//}}

//{{Redefine Member Section
//}}

//{{Redefine Method Section
#define	addGcDbObject 	addOdDbObject
#define	appendGcDbEntity 	appendOdDbEntity
#define	createGCADDevice 	createCADDevice
#define	createGCADOffScreenDevice 	createCADOffScreenDevice
#define	createGCADModel 	createCADModel
#define	createGCADView 	createCADView
#define	createGCADViewport 	createCADViewport
#define	destroyGCADDevice 	destroyCADDevice
#define	destroyGCADModel 	destroyCADModel
#define	destroyGCADView 	destroyCADView
#define	getGcDbHandle 	getOdDbHandle
#define	getGcDbObjectId 	getOdDbObjectId
#define	readGcDbHandle 	readOdDbHandle
#define	setGcDbObjectIdsInFlux 	setOdDbObjectIdsInFlux
#define	treatAsGcDbBlockRefForExplode 	treatAsOdDbBlockRefForExplode
#define	writeGcDbHandle 	writeOdDbHandle
#define gcdbSetReferenced oddbSetReferenced
//}}

//{{Redefine Struct Section
#define	GcDbSymUtilServices 	OdDbSymUtilServices
#define	GcDbSymbolUtilities 	OdDbSymUtil
#define	GcDbSymUtil 		OdDbSymUtil
#define GcTimeStamp           OdTimeStamp
#define	GcGiClipBoundary 	OdGiClipBoundary
#define	GcGiRequestScanLines 	OdGiRequestScanLines /* unimplemented */
#define	GcGiSentScanLines 	OdGiSentScanLines    /* unimplemented */
#define	GcGsClientViewInfo 	OdGsClientViewInfo
#define	GcRx  OdRx
#define GcFd  OdFd
#define HcInt32  OdInt32
#define GcIntArray OdIntArray
#define GcBoolArray OdBoolArray
#define GcDoubleArray OdDoubleArray
//}}

//{{dynamic blocks
#define GcDbEvalGraph OdDbEvalGraph
#define GcDbEvalExpr OdDbEvalExpr
#define GcDbEvalConnectable OdDbEvalConnectable
#define GcDbEvalContext OdDbEvalContext
#define GcDbEvalContextIterator OdDbEvalContextIterator
#define GcDbBlockElement OdDbBlockElement
#define GcDbBlockParameter OdDbBlockParameter
#define GcDbBlock1PtParameter OdDbBlock1PtParameter
#define GcDbBlockPointParameter OdDbBlockPointParameter
#define GcDbBlockGrip OdDbBlockGrip
#define GcDbBlockXYGrip OdDbBlockXYGrip
#define GcDbBlockGripExpr OdDbBlockGripExpr
#define GcDbBlockAction OdDbBlockAction
#define GcDbBlockMoveAction OdDbBlockMoveAction
#define GcDbBlockLinearGrip OdDbBlockLinearGrip
#define GcDbBlockStretchAction OdDbBlockStretchAction
#define GcDbBlock2PtParameter OdDbBlock2PtParameter
#define GcDbBlockLinearParameter OdDbBlockLinearParameter
#define GcDbBlockPolarParameter OdDbBlockPolarParameter
#define GcDbBlockPolarGrip OdDbBlockPolarGrip
#define GcDbBlockActionWithBasePt OdDbBlockActionWithBasePt
#define GcDbBlockScaleAction OdDbBlockScaleAction
#define GcDbBlockRotationParameter OdDbBlockRotationParameter
#define GcDbBlockRotationGrip OdDbBlockRotationGrip
#define GcDbBlockRotateAction OdDbBlockRotateAction
#define GcDbBlockFlipParameter OdDbBlockFlipParameter
#define GcDbBlockFlipGrip OdDbBlockFlipGrip
#define GcDbBlockFlipAction OdDbBlockFlipAction
#define GcDbBlockXYParameter OdDbBlockXYParameter
#define GcDbBlockArrayAction OdDbBlockArrayAction
#define GcDbBlockLookUpParameter OdDbBlockLookUpParameter
#define GcDbBlockLookupGrip OdDbBlockLookupGrip
#define GcDbBlockLookupAction OdDbBlockLookupAction
#define GcDbBlockAlignmentParameter OdDbBlockAlignmentParameter
#define GcDbBlockAlignmentGrip OdDbBlockAlignmentGrip
#define GcDbBlockBasepointParameter OdDbBlockBasepointParameter
#define GcDbBlockVisibilityParameter OdDbBlockVisibilityParameter
#define GcDbBlockVisibilityGrip OdDbBlockVisibilityGrip
#define GcDbBlockPolarStretchAction OdDbBlockPolarStretchAction
#define GcDbBlockRepresentationData OdDbBlockRepresentationData
#define GcDbDynamicBlockPurgePreventer OdDbDynamicBlockPurgePreventer
#define GcDbDynBlockReferenceProperty OdDbDynBlockReferenceProperty
#define GcDbDynBlockReferencePropertyArray OdDbDynBlockReferencePropertyArray
#define GcDbEvalNodeId OdDbEvalNodeId
#define GcDbEvalNodeIdArray OdDbEvalNodeIdArray
#define GcDbConnectionPoint OdDbConnectionPoint
#define GcDbEvalVariantArray OdDbEvalVariantArray
#define GcDbBlkParamPropertyDescriptor OdDbBlkParamPropertyDescriptor
#define GcDbBlockStretchEntityItem OdDbBlockStretchEntityItem
#define GcDbBlockStretchNodeItem OdDbBlockStretchNodeItem
#define GcDbBlockActionXYType OdDbBlockActionXYType
#define GcDbBlockParamValueSet OdDbBlockParamValueSet

#define GcDbUpdateDynBlockReferenceProperty OdDbUpdateDynBlockReferenceProperty
#define GcDbObtainDynBlockReferenceProperty OdDbObtainDynBlockReferenceProperty
#define GcDbUpdateDynamicBlockReference OdDbUpdateDynamicBlockReference
//}}

#define GcDbDwfDefinition OdDbDwfDefinition
#define GcDbAnnotationScale OdDbAnnotationScale
#define GcDbObjectContext OdDbObjectContext
#define GcDbObjectContextManager OdDbObjectContextManager
#define GcDbObjectContextCollection OdDbObjectContextCollection
#define GcDbObjectContextCollectionIterator OdDbObjectContextCollectionIterator
#define GcDbTableContent OdDbTableContent
#define GcDbTableTemplate OdDbTableTemplate
#define GcValue OdValue
#define GcDbPdfDefinition OdDbPdfDefinition
#define gcdbGetCurrentDwfHost oddbGetCurrentDwfHost
#define GcDbHandleArrayPtRef OdDbHandleArrayPtRef
#define GcDbLoftedSurface OdDbLoftedSurface 

#define GcFileDependencyInfo OdFileDependencyInfo
#define GcFileDependencyManager OdFileDependencyManager
#define GCDB_MODEL_SPACE ACDB_MODEL_SPACE
#define GCDB_PAPER_SPACE ACDB_PAPER_SPACE


#define GcRectangle3d OdRectangle3d
#define GcDbIndexFilterManager OdDbIndexFilterManager

//{{redefine Constraints
#define GcDbAssocAction OdDbAssocAction
#define GcDbAssocStatus OdDbAssocStatus
#define GcDbAssocNetwork OdDbAssocNetwork
#define GcDbAssoc2dConstraintGroup OdDbAssoc2dConstraintGroup
#define GcConstrainedGeometry OdConstrainedGeometry
#define GcGeomConstraint	  OdGeomConstraint
#define GcDbAssocManager	OdDbAssocManager
#define GcConstraintGroupNodeId	OdConstraintGroupNodeId
#define GcDbAssocDependency OdDbAssocDependency
#define GcDbAssocGeomDependency	OdDbAssocGeomDependency
#define GcConstrainedImplicitPoint	OdConstrainedImplicitPoint
#define GcTangentConstraint		OdTangentConstraint
#define GcColinearConstraint	OdColinearConstraint
#define GcCenterPointConstraint	OdCenterPointConstraint
#define GcConcentricConstraint  OdConcentricConstraint
#define GcG2SmoothConstraint	OdG2SmoothConstraint
#define GcCompositeConstraint	OdCompositeConstraint
#define GcEqualCurvatureConstraint	OdEqualCurvatureConstraint
#define GcEqualDistanceConstraint	OdEqualDistanceConstraint
#define GcEqualLengthConstraint		OdEqualLengthConstraint
#define GcFixedConstraint			OdFixedConstraint
#define GcNormalConstraint			OdNormalConstraint
#define GcHorizontalConstraint		OdHorizontalConstraint
#define GcVerticalConstraint		OdVerticalConstraint
#define GcParallelConstraint		OdParallelConstraint
#define GcPerpendicularConstraint	OdPerpendicularConstraint
#define GcPointCoincidenceConstraint	OdPointCoincidenceConstraint
#define GcSymmetricConstraint	OdSymmetricConstraint
#define GcEqualHelpParameterConstraint	OdEqualHelpParameterConstraint
#define GcExplicitConstraint	OdExplicitConstraint
#define GcEqualRadiusConstraint	OdEqualRadiusConstraint
#define GcPointCurveConstraint	OdPointCurveConstraint
#define GcConstrainedCircle		OdConstrainedCircle
#define GcConstrainedEllipse	OdConstrainedEllipse
#define GcConstrainedLine		OdConstrainedLine
#define GcConstrainedPoint		OdConstrainedPoint
#define GcConstrainedSpline		OdConstrainedSpline
#define GcConstrainedCurve		OdConstrainedCurve
#define GcConstrainedRigidSet	OdConstrainedRigidSet
#define GcDbAssocPersSubentIdPE	OdDbAssocPersSubentIdPE
#define GcDbAssocVariable		OdDbAssocVariable
#define GcDbAssocValueDependency	OdDbAssocValueDependency
#define GcDbAssocDimDependencyBody	OdDbAssocDimDependencyBody
#define GcDistanceConstraint		OdDistanceConstraint
#define GcDbCompoundObjectId		OdDbCompoundObjectId
#define GcAngleConstraint			OdAngleConstraint
#define Gc3PointAngleConstraint		Od3PointAngleConstraint
#define GcDbAssocActionBody OdDbAssocActionBody
#define GcDbAssocParamBasedActionBody OdDbAssocParamBasedActionBody
#define GcDbAssocArrayActionBody  OdDbAssocArrayActionBody
#define GcDbAssocArrayParameters  OdDbAssocArrayParameters
#define GcDbItemLocator OdDbItemLocator
#define GcDbAssocActionParam OdDbAssocActionParam
#define GcDbGeomRef OdDbGeomRef
#define GcDbAssocArrayPathParameters OdDbAssocArrayPathParameters
#define GcDbAssocArrayPolarParameters OdDbAssocArrayPolarParameters
#define GcDbAssocArrayRectangularParameters OdDbAssocArrayRectangularParameters
#define GcDbAssocArrayCommonParameters OdDbAssocArrayCommonParameters
#define GcDbVertexRef                  OdDbVertexRef
//}}

#define GcDbModelDocViewStyle OdDbModelDocViewStyle
#define GcDbDetailViewStyle   OdDbDetailViewStyle
#define GcDbSectionViewStyle  OdDbSectionViewStyle

//{{redefine PointCloud
#define GcDbPointCloud        	OdDbPointCloud
#define GcDbPointCloudDef	OdDbPointCloudDef
#define GcDbPointCloudEx	OdDbPointCloudEx
#define GcDbPointCloudDefEx	OdDbPointCloudDefEx
#define GcDbPointCloudCrop	OdDbPointCloudCropping
#define GcDbPointCloudColorMap	OdDbPointCloudColorMap
//}}


#define GcDbShHistory               OdDbShHistory
#define GcDbAssocPersSubentManager  OdDbAssocPersSubentManager 
#define GcDbShHistoryNode           OdDbShHistoryNode
#define GcDbShBoolean               OdDbShBoolean 
#define GcDbShPrimitive             OdDbShPrimitive
#define GcDbShBox                   OdDbShBox 
#define GcDbShBrep                  OdDbShBrep 
#define GcDbShChamfer               OdDbShChamfer 
#define GcDbShCylinder              OdDbShCylinder 
#define GcDbShExtrusion             OdDbShExtrusion 
#define GcDbShFillet                OdDbShFillet 
#define GcDbShLoft                  OdDbShLoft 
#define GcDbShPyramid               OdDbShPyramid 
#define GcDbShRevolve               OdDbShRevolve 
#define GcDbShSphere                OdDbShSphere 
#define GcDbShSubentColor           OdDbShSubentColor 
#define GcDbShSubentMaterial        OdDbShSubentMaterial 
#define GcDbShSweep                 OdDbShSweep 
#define GcDbShTorus                 OdDbShTorus 
#define GcDbShWedge                 OdDbShWedge 

#define GcDb3dProfile               OdDb3dProfile
#define GcDb3dProfileData           OdDb3dProfileData
#define GcDbLoftProfile             OdDbLoftProfile





