#pragma once
#include <assert.h>
#include "acadstrc.h"
#include "dbsymutl.h"
#include "../OdSymUtl.h"

#define ACEDSYMUTIL_SERVICES_CURRENT_VERSION  GCEDSYMUTIL_SERVICES_CURRENT_VERSION
#define GCEDSYMUTIL_SERVICES_CURRENT_VERSION  ODEDSYMUTIL_SERVICES_CURRENT_VERSION

#define AcEdSymbolUtilities  GcEdSymbolUtilities
#define GcEdSymbolUtilities  OdEdSymbolUtilities  

#define ACEDSYMUTIL_SERVICESNAME_WITH_VERSION_1  GCEDSYMUTIL_SERVICESNAME_WITH_VERSION_1
#define GCEDSYMUTIL_SERVICESNAME_WITH_VERSION_1  ODEDSYMUTIL_SERVICESNAME_WITH_VERSION_1

#define ACEDSYMUTIL_SERVICESNAME_WITH_VERSION  GCEDSYMUTIL_SERVICESNAME_WITH_VERSION
#define GCEDSYMUTIL_SERVICESNAME_WITH_VERSION  ODEDSYMUTIL_SERVICESNAME_WITH_VERSION

#define ACEDSYMUTIL_SERVICES_NAME  GCEDSYMUTIL_SERVICES_NAME
#define GCEDSYMUTIL_SERVICES_NAME  ODEDSYMUTIL_SERVICES_NAME

#define AcEdSymUtil  GcEdSymUtil
#define GcEdSymUtil  OdEdSymUtil

#define AcEdSymUtilServices  GcEdSymUtilServices
#define GcEdSymUtilServices  OdEdSymUtilServices

#define acedSymUtil  gcedSymUtil
#define gcedSymUtil  odedSymUtil

