#pragma once

#define ACRX_CLASS_DICTIONARY           GCRX_CLASS_DICTIONARY
#define GCRX_CLASS_DICTIONARY           ODRX_CLASS_DICTIONARY
#define ACRX_DYNAMIC_LINKER             GCRX_DYNAMIC_LINKER
#define GCRX_DYNAMIC_LINKER             ODRX_DYNAMIC_LINKER
#define ACRX_SERVICE_DICTIONARY         GCRX_SERVICE_DICTIONARY
#define GCRX_SERVICE_DICTIONARY         ODRX_SERVICE_DICTIONARY
#define ACRX_KERNEL_SERVICES            GCRX_KERNEL_SERVICES
#define GCRX_KERNEL_SERVICES            ODRX_KERNEL_SERVICES
#define ACRX_PROTOCOL_REACTOR_MANAGER   GCRX_PROTOCOL_REACTOR_MANAGER
#define GCRX_PROTOCOL_REACTOR_MANAGER   ODRX_PROTOCOL_REACTOR_MANAGER

#include "../RxNames.h"

